-- 初始化经典医案数据

-- 张仲景医案 - 桂枝汤
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '张仲景',
  '汉代',
  '男',
  35,
  '发热、头痛、汗出、恶风',
  '患者因外感风寒，出现发热头痛，伴有汗出恶风，脉浮缓。',
  '舌淡苔薄白',
  '浮缓',
  '太阳中风证',
  '桂枝汤',
  '桂枝9g，芍药9g，甘草6g，生姜9g，大枣4枚',
  '水煎服，每日一剂，分三次服',
  '服药后喝热粥，微汗出而愈',
  '此为太阳中风证之经典方，解肌发表，调和营卫',
  '《伤寒论》',
  ARRAY['太阳病', '发热', '头痛', '汗出', '恶风'],
  ARRAY['发热', '头痛', '汗出', '恶风', '太阳中风'],
  '太阳病-桂枝汤证',
  0.95,
  NOW(),
  NOW()
);

-- 张仲景医案 - 麻黄汤
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '张仲景',
  '汉代',
  '男',
  28,
  '发热、恶寒、无汗、头痛、身痛',
  '患者因外感风寒，发热恶寒，无汗，全身酸痛，脉浮紧。',
  '舌淡苔薄白',
  '浮紧',
  '太阳伤寒证',
  '麻黄汤',
  '麻黄9g，桂枝6g，甘草3g，杏仁12g',
  '水煎服，每日一剂，分三次服',
  '服药后汗出而愈',
  '此为太阳伤寒证，发汗解表',
  '《伤寒论》',
  ARRAY['太阳病', '发热', '恶寒', '无汗', '头痛', '身痛'],
  ARRAY['发热', '恶寒', '无汗', '头痛', '身痛', '太阳伤寒'],
  '太阳病-麻黄汤证',
  0.94,
  NOW(),
  NOW()
);

-- 张仲景医案 - 小柴胡汤
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '张仲景',
  '汉代',
  '女',
  42,
  '往来寒热、胸胁苦满、口苦、咽干、目眩',
  '患者因少阳经气不利，出现往来寒热，胸胁苦满，口苦咽干目眩。',
  '舌边红苔薄黄',
  '弦',
  '少阳病',
  '小柴胡汤',
  '柴胡12g，黄芩9g，人参6g，甘草6g，半夏9g，生姜9g，大枣4枚',
  '水煎服，每日一剂，分三次服',
  '服药三剂后症状明显缓解',
  '此为少阳病，和解少阳',
  '《伤寒论》',
  ARRAY['少阳病', '往来寒热', '胸胁苦满', '口苦', '咽干', '目眩'],
  ARRAY['往来寒热', '胸胁苦满', '口苦', '咽干', '目眩', '少阳病'],
  '少阳病-小柴胡汤证',
  0.93,
  NOW(),
  NOW()
);

-- 李可医案 - 破格救心汤
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '李可',
  '现代',
  '男',
  65,
  '心悸、气短、畏寒肢冷、面色苍白',
  '患者因心肾阳衰，出现心悸气短，畏寒肢冷，面色苍白，脉微欲绝。',
  '舌淡苔白滑',
  '微弱',
  '心肾阳衰',
  '破格救心汤',
  '附子100g（先煎2小时），干姜30g，炙甘草30g，人参15g，山萸肉30g，生龙骨30g，生牡蛎30g',
  '附子先煎2小时，其余后下，水煎服，每日一剂',
  '服药五剂后心悸气短明显改善，四肢转温',
  '此为心肾阳衰之危重证，温阳救逆',
  '《李可老中医急危重症疑难病经验专辑》',
  ARRAY['心肾阳衰', '心悸', '气短', '畏寒', '肢冷'],
  ARRAY['心悸', '气短', '畏寒', '肢冷', '阳衰'],
  '心肾阳衰',
  0.92,
  NOW(),
  NOW()
);

-- 李可医案 - 四逆汤加味
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '李可',
  '现代',
  '女',
  55,
  '腹痛、腹泻、四肢厥冷、脉微细',
  '患者因脾胃阳衰，出现腹痛腹泻，四肢厥冷，脉微细。',
  '舌淡苔白',
  '微细',
  '脾胃阳衰',
  '四逆汤加味',
  '附子60g（先煎2小时），干姜30g，炙甘草30g，白术15g，茯苓15g',
  '附子先煎2小时，其余后下，水煎服，每日一剂',
  '服药三剂后腹泻止，四肢转温',
  '此为脾胃阳衰，温中健脾',
  '《李可老中医急危重症疑难病经验专辑》',
  ARRAY['脾胃阳衰', '腹痛', '腹泻', '四肢厥冷'],
  ARRAY['腹痛', '腹泻', '四肢厥冷', '阳衰'],
  '脾胃阳衰',
  0.91,
  NOW(),
  NOW()
);

-- 孙思邈医案 - 温胆汤
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '孙思邈',
  '唐代',
  '女',
  38,
  '心烦失眠、胆怯易惊、头晕目眩、恶心呕吐',
  '患者因胆胃不和，痰热内扰，出现心烦失眠，胆怯易惊，头晕目眩，恶心呕吐。',
  '舌红苔黄腻',
  '弦滑',
  '胆胃不和、痰热内扰',
  '温胆汤',
  '半夏12g，竹茹12g，枳实9g，陈皮9g，茯苓12g，甘草6g，生姜6g，大枣3枚',
  '水煎服，每日一剂，分三次服',
  '服药七剂后症状明显改善',
  '此为胆胃不和、痰热内扰，清热化痰，和胃安神',
  '《千金要方》',
  ARRAY['胆胃不和', '痰热', '失眠', '心烦', '易惊'],
  ARRAY['失眠', '心烦', '易惊', '痰热'],
  '胆胃不和-痰热内扰',
  0.90,
  NOW(),
  NOW()
);

-- 黄煌医案 - 桂枝茯苓丸
INSERT INTO medical_cases (
  id,
  doctor_name,
  doctor_era,
  patient_gender,
  patient_age,
  main_symptoms,
  current_illness,
  tongue,
  pulse,
  diagnosis,
  prescription_name,
  prescription_composition,
  prescription_dosage,
  prescription_usage,
  treatment_result,
  notes,
  source,
  tags,
  symptom_keywords,
  diagnosis_pattern,
  effectiveness_score,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  '黄煌',
  '当代',
  '女',
  45,
  '痛经、月经有块、腹部疼痛固定',
  '患者因血瘀胞宫，出现痛经，月经有血块，腹部疼痛固定，舌暗紫，脉涩。',
  '舌暗紫有瘀斑',
  '涩',
  '血瘀胞宫',
  '桂枝茯苓丸',
  '桂枝9g，茯苓9g，牡丹皮9g，桃仁9g，赤芍9g',
  '水煎服，每日一剂，分三次服',
  '服药一个月后痛经明显减轻',
  '此为血瘀胞宫，活血化瘀',
  '《经方100首》',
  ARRAY['血瘀', '痛经', '月经有块', '腹痛'],
  ARRAY['痛经', '月经有块', '血瘀'],
  '血瘀胞宫',
  0.89,
  NOW(),
  NOW()
);
