/**
 * 扩展方证数据 - 补充200+经典方剂
 * 按《伤寒论》《金匮要略》分类
 */

import { FormulaEvidence, TreatmentMethod } from './advanced/ontology-types';

// 重新导出类型，方便外部使用
export type { FormulaEvidence, TreatmentMethod };

// ============================================
// 太阳病方剂（50个）
// ============================================

export const SUNYANG_FORMULAS: Record<string, FormulaEvidence> = {
  // 桂枝汤系列（15个）
  桂枝汤: {
    formula: '桂枝汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳中风，阳浮而阴弱，阳浮者，热自发；阴弱者，汗自出。啬啬恶寒，淅淅恶风，翕翕发热，鼻鸣干呕者，桂枝汤主之。',
    keySymptoms: ['恶风', '发热', '汗出', '头痛', '脉浮缓'],
    mechanism: '营卫不和，卫气不固，营阴外泄',
    treatmentMethod: '调和营卫',
    indications: ['太阳中风表虚证', '营卫不和', '自汗出'],
    contraindications: ['表实证无汗', '里热证', '温病初起'],
    dosage: '桂枝9g，芍药9g，炙甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服，服后啜热稀粥，覆衣被取微似汗，不可令大汗淋漓。',
  },
  桂枝加葛根汤: {
    formula: '桂枝加葛根汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，项背强几几，反汗出恶风者，桂枝加葛根汤主之。',
    keySymptoms: ['项背强几几', '汗出', '恶风', '发热', '脉浮'],
    mechanism: '太阳病经气不利，营卫不和',
    treatmentMethod: '调和营卫',
    indications: ['太阳病兼项背强痛', '营卫不和'],
    contraindications: ['项背强痛而无汗者'],
    dosage: '葛根12g，桂枝6g，芍药6g，炙甘草6g，生姜9g，大枣4枚',
    instructions: '水煎服，先煮葛根，后内诸药。',
  },
  桂枝加厚朴杏子汤: {
    formula: '桂枝加厚朴杏子汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '喘家作，桂枝汤加厚朴、杏子佳。',
    keySymptoms: ['喘', '汗出', '恶风', '发热', '咳嗽'],
    mechanism: '太阳表虚，肺气不降',
    treatmentMethod: '调和营卫',
    indications: ['太阳中风兼喘', '表虚证兼喘'],
    contraindications: ['表实证喘'],
    dosage: '桂枝9g，芍药9g，炙甘草6g，生姜9g，大枣12枚，厚朴6g，杏仁9g',
    instructions: '水煎服。',
  },
  桂枝加附子汤: {
    formula: '桂枝加附子汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，发汗，遂漏不止，其人恶风，小便难，四肢微急，难以屈伸者，桂枝加附子汤主之。',
    keySymptoms: ['汗漏不止', '恶风', '小便难', '四肢微急'],
    mechanism: '太阳病发汗太过，表阳不固，阳虚液脱',
    treatmentMethod: '调和营卫',
    indications: ['太阳病发汗后阳虚漏汗', '表阳虚'],
    contraindications: ['表实无汗', '里热证'],
    dosage: '桂枝9g，芍药9g，炙甘草6g，生姜9g，大枣12枚，附子6g（炮）',
    instructions: '水煎服。',
  },
  桂枝去芍药汤: {
    formula: '桂枝去芍药汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，下之后，脉促胸满者，桂枝去芍药汤主之。',
    keySymptoms: ['脉促', '胸满', '发热', '恶风'],
    mechanism: '太阳病误下，表邪不解，胸阳被抑',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下胸满', '表邪内陷'],
    contraindications: ['胸腹俱痛'],
    dosage: '桂枝9g，炙甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服。',
  },
  桂枝去芍药加附子汤: {
    formula: '桂枝去芍药加附子汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '若微寒者，桂枝去芍药加附子汤主之。',
    keySymptoms: ['脉促', '胸满', '微恶寒', '四肢不温'],
    mechanism: '太阳病误下，表阳受损，胸阳不运',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下胸满恶寒', '表阳虚'],
    contraindications: ['热证胸满'],
    dosage: '桂枝9g，炙甘草6g，生姜9g，大枣12枚，附子6g（炮）',
    instructions: '水煎服。',
  },
  桂枝加芍药生姜各一两人参三两新加汤: {
    formula: '桂枝加芍药生姜各一两人参三两新加汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '发汗后，身疼痛，脉沉迟者，桂枝加芍药生姜各一两人参三两新加汤主之。',
    keySymptoms: ['身疼痛', '脉沉迟', '汗出', '恶风'],
    mechanism: '发汗后气营两虚，经络失养',
    treatmentMethod: '调和营卫',
    indications: ['发汗后身痛脉沉迟', '气血两虚'],
    contraindications: ['表实证身痛'],
    dosage: '桂枝9g，芍药12g，炙甘草6g，生姜12g，大枣12枚，人参9g',
    instructions: '水煎服。',
  },
  桂枝加桂汤: {
    formula: '桂枝加桂汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '烧针令其汗，针处被寒，核起而赤者，必发奔豚，气从少腹上冲心者，灸其核上各一壮，与桂枝加桂汤，更加桂二两也。',
    keySymptoms: ['气从少腹上冲心', '脐下悸', '心悸'],
    mechanism: '心阳受损，下焦寒气上逆',
    treatmentMethod: '调和营卫',
    indications: ['奔豚证', '心阳虚寒气上逆'],
    contraindications: ['心阳不虚的气上冲'],
    dosage: '桂枝15g，芍药9g，炙甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服。',
  },
  桂枝加龙骨牡蛎汤: {
    formula: '桂枝加龙骨牡蛎汤',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '夫失精家，少腹弦急，阴头寒，目眩，发落，脉极虚芤迟，为清谷，亡血，失精。脉得诸芤动微紧，男子失精，女子梦交，桂枝加龙骨牡蛎汤主之。',
    keySymptoms: ['遗精', '少腹弦急', '阴头寒', '目眩', '发落', '脉极虚芤迟'],
    mechanism: '阴阳两虚，心肾不交，虚阳外越',
    treatmentMethod: '调和营卫',
    indications: ['阴阳两虚遗精', '虚劳失精'],
    contraindications: ['实证遗精'],
    dosage: '桂枝9g，芍药9g，炙甘草6g，生姜9g，大枣12枚，龙骨15g，牡蛎15g',
    instructions: '水煎服。',
  },
  桂枝去芍药加蜀漆牡蛎龙骨救逆汤: {
    formula: '桂枝去芍药加蜀漆牡蛎龙骨救逆汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒脉浮，医以火迫劫之，亡阳，必惊狂，卧起不安者，桂枝去芍药加蜀漆牡蛎龙骨救逆汤主之。',
    keySymptoms: ['惊狂', '卧起不安', '心悸', '脉浮'],
    mechanism: '火劫亡阳，神不守舍，痰火扰心',
    treatmentMethod: '调和营卫',
    indications: ['火劫亡阳惊狂', '痰火扰心'],
    contraindications: ['无痰火的惊狂'],
    dosage: '桂枝9g，炙甘草6g，生姜9g，大枣12枚，蜀漆9g，牡蛎15g，龙骨15g',
    instructions: '水煎服，蜀漆先煎去沫。',
  },
  桂枝甘草汤: {
    formula: '桂枝甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '发汗过多，其人叉手自冒心，心下悸，欲得按者，桂枝甘草汤主之。',
    keySymptoms: ['心下悸', '欲得按', '叉手自冒心'],
    mechanism: '发汗过多，心阳受损',
    treatmentMethod: '调和营卫',
    indications: ['心阳虚心悸', '汗后心悸'],
    contraindications: ['心阳不虚的心悸'],
    dosage: '桂枝12g，炙甘草6g',
    instructions: '水煎服。',
  },
  桂枝甘草龙骨牡蛎汤: {
    formula: '桂枝甘草龙骨牡蛎汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '火逆下之，因烧针烦躁者，桂枝甘草龙骨牡蛎汤主之。',
    keySymptoms: ['烦躁', '心悸', '惊惕'],
    mechanism: '火逆伤阳，神浮心悸',
    treatmentMethod: '调和营卫',
    indications: ['火逆烦躁', '心神不宁'],
    contraindications: ['热证烦躁'],
    dosage: '桂枝6g，炙甘草6g，龙骨15g，牡蛎15g',
    instructions: '水煎服。',
  },
  桂枝人参汤: {
    formula: '桂枝人参汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，外证未除，而数下之，遂协热而利，利下不止，心下痞硬，表里不解者，桂枝人参汤主之。',
    keySymptoms: ['利下不止', '心下痞硬', '发热', '恶风'],
    mechanism: '表证未解，脾胃虚寒，协热下利',
    treatmentMethod: '调和营卫',
    indications: ['表里不解下利', '脾胃虚寒下利'],
    contraindications: ['热性下利'],
    dosage: '桂枝12g，炙甘草12g，白术9g，人参9g，干姜9g',
    instructions: '水煎服。',
  },
  桂枝附子汤: {
    formula: '桂枝附子汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒八九日，风湿相搏，身体疼烦，不能自转侧，不呕不渴，脉浮虚而涩者，桂枝附子汤主之。',
    keySymptoms: ['身体疼烦', '不能自转侧', '脉浮虚而涩'],
    mechanism: '风湿相搏，表阳虚，经络不利',
    treatmentMethod: '调和营卫',
    indications: ['风湿痹痛', '表阳虚'],
    contraindications: ['风湿热痹'],
    dosage: '桂枝12g，附子9g（炮），生姜9g，大枣3枚，炙甘草6g',
    instructions: '水煎服。',
  },
  桂枝去桂加茯苓白术汤: {
    formula: '桂枝去桂加茯苓白术汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '服桂枝汤，或下之，仍头项强痛，翕翕发热，无汗，心下满微痛，小便不利者，桂枝去桂加茯苓白术汤主之。',
    keySymptoms: ['头项强痛', '发热', '无汗', '心下满微痛', '小便不利'],
    mechanism: '水饮内停，太阳经气不利',
    treatmentMethod: '化饮',
    indications: ['水饮内停表证', '心下水饮'],
    contraindications: ['表实无水饮'],
    dosage: '芍药9g，炙甘草6g，生姜9g，大枣12枚，茯苓9g，白术9g',
    instructions: '水煎服。',
  },

  // 麻黄汤系列（8个）
  麻黄汤: {
    formula: '麻黄汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，头痛发热，身疼腰痛，骨节疼痛，恶风无汗而喘者，麻黄汤主之。',
    keySymptoms: ['恶寒', '发热', '无汗', '头痛身痛', '喘', '脉浮紧'],
    mechanism: '风寒束表，营卫郁闭，肺气不宣',
    treatmentMethod: '解表',
    indications: ['太阳伤寒表实证', '风寒束表'],
    contraindications: ['表虚有汗', '体虚者慎用', '阳虚体弱'],
    dosage: '麻黄9g，桂枝6g，杏仁9g，炙甘草3g',
    instructions: '水煎服，先煮麻黄去沫，温服覆取微似汗。',
  },
  麻黄杏仁甘草石膏汤: {
    formula: '麻黄杏仁甘草石膏汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '发汗后，不可更行桂枝汤。汗出而喘，无大热者，可与麻黄杏仁甘草石膏汤。',
    keySymptoms: ['汗出而喘', '发热', '口渴', '脉数'],
    mechanism: '邪热壅肺，肺气不降',
    treatmentMethod: '清热',
    indications: ['邪热壅肺', '汗出而喘'],
    contraindications: ['风寒喘'],
    dosage: '麻黄12g，杏仁9g，炙甘草6g，石膏24g',
    instructions: '水煎服，先煮麻黄，后纳石膏。',
  },
  麻黄加术汤: {
    formula: '麻黄加术汤',
    source: '金匮要略',
    chapter: '痉湿暍病篇',
    originalText: '湿家身烦疼，可与麻黄加术汤发其汗为宜，慎不可以火攻之。',
    keySymptoms: ['身烦疼', '恶寒', '无汗', '脉浮紧'],
    mechanism: '寒湿在表，经络阻滞',
    treatmentMethod: '解表',
    indications: ['寒湿在表', '风湿痹痛'],
    contraindications: ['风湿热痹'],
    dosage: '麻黄9g，桂枝6g，甘草3g，杏仁9g，白术12g',
    instructions: '水煎服。',
  },
  麻黄附子甘草汤: {
    formula: '麻黄附子甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，得之二三日，麻黄附子甘草汤微发汗。以二三日无证，故微发汗也。',
    keySymptoms: ['恶寒', '发热', '无汗', '脉沉'],
    mechanism: '少阴感寒，阳气不足',
    treatmentMethod: '温经散寒',
    indications: ['少阴感寒', '阳虚外感'],
    contraindications: ['少阴热化证'],
    dosage: '麻黄6g，附子6g（炮），炙甘草3g',
    instructions: '水煎服。',
  },
  麻黄附子细辛汤: {
    formula: '麻黄附子细辛汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，始得之，反发热，脉沉者，麻黄附子细辛汤主之。',
    keySymptoms: ['发热', '恶寒', '无汗', '脉沉'],
    mechanism: '少阴感寒，阳气被郁',
    treatmentMethod: '温经散寒',
    indications: ['少阴感寒初起', '阳虚外感'],
    contraindications: ['少阴热化证'],
    dosage: '麻黄6g，附子6g（炮），细辛3g',
    instructions: '水煎服。',
  },
  麻黄连轺赤小豆汤: {
    formula: '麻黄连轺赤小豆汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒瘀热在里，身必黄，麻黄连轺赤小豆汤主之。',
    keySymptoms: ['身黄', '发热', '无汗', '小便不利'],
    mechanism: '湿热郁表，外不得越，内不得泄',
    treatmentMethod: '解表',
    indications: ['湿热发黄', '表证发黄'],
    contraindications: ['寒湿发黄'],
    dosage: '麻黄6g，连轺6g，杏仁6g，赤小豆30g，大枣12枚，生姜6g，甘草6g',
    instructions: '水煎服，先煮麻黄。',
  },
  麻黄升麻汤: {
    formula: '麻黄升麻汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒六七日，大下后，寸脉沉而迟，手足厥逆，下部脉不至，喉咽不利，唾脓血，泄利不止者，为难治。麻黄升麻汤主之。',
    keySymptoms: ['咽喉不利', '唾脓血', '泄利不止', '手足厥逆'],
    mechanism: '邪陷厥阴，上热下寒，肺热脾寒',
    treatmentMethod: '清上温下',
    indications: ['上热下寒', '肺热脾寒'],
    contraindications: ['单纯热证或寒证'],
    dosage: '麻黄9g，升麻9g，当归6g，知母6g，黄芩6g，葳蕤6g，芍药3g，天冬3g，桂枝3g，茯苓3g，甘草3g，石膏3g，白术3g，干姜3g',
    instructions: '水煎服，先煮麻黄。',
  },
  葛根汤: {
    formula: '葛根汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，项背强几几，无汗恶风，葛根汤主之。',
    keySymptoms: ['项背强几几', '无汗', '恶风', '发热', '脉浮紧'],
    mechanism: '风寒束表，太阳经气不利',
    treatmentMethod: '解表',
    indications: ['太阳病项背强痛', '风寒束表'],
    contraindications: ['项背强痛有汗者'],
    dosage: '葛根12g，麻黄9g，桂枝6g，芍药6g，炙甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服，先煮葛根、麻黄。',
  },

  // 大青龙汤系列（3个）
  大青龙汤: {
    formula: '大青龙汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳中风，脉浮紧，发热恶寒，身疼痛，不汗出而烦躁者，大青龙汤主之。',
    keySymptoms: ['发热', '恶寒', '身疼痛', '无汗', '烦躁', '脉浮紧'],
    mechanism: '风寒束表，内有郁热',
    treatmentMethod: '解表',
    indications: ['风寒束表兼内热', '表寒里热'],
    contraindications: ['表虚有汗', '脉微弱，汗出恶风'],
    dosage: '麻黄12g，桂枝6g，甘草6g，杏仁6g，石膏18g，生姜9g，大枣4枚',
    instructions: '水煎服，先煮麻黄，温服取微似汗。',
  },
  小青龙汤: {
    formula: '小青龙汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒表不解，心下有水气，干呕发热而咳，或渴，或利，或噎，或小便不利，少腹满，或喘者，小青龙汤主之。',
    keySymptoms: ['发热', '恶寒', '干呕', '咳嗽', '痰稀', '无汗', '喘'],
    mechanism: '外寒内饮，水寒射肺',
    treatmentMethod: '化饮',
    indications: ['外寒内饮', '寒饮咳嗽'],
    contraindications: ['风热咳嗽', '阴虚咳嗽'],
    dosage: '麻黄9g，芍药9g，细辛3g，干姜6g，炙甘草6g，桂枝9g，五味子6g，半夏9g',
    instructions: '水煎服，先煮麻黄。',
  },
  文蛤汤: {
    formula: '文蛤汤',
    source: '金匮要略',
    chapter: '呕吐哕下利病篇',
    originalText: '吐后，渴欲得水而贪饮者，文蛤汤主之。',
    keySymptoms: ['渴欲饮水', '心烦', '发热', '脉浮'],
    mechanism: '水热互结，津伤气耗',
    treatmentMethod: '清热',
    indications: ['水热互结口渴', '吐后渴饮'],
    contraindications: ['阴虚燥渴'],
    dosage: '文蛤15g，麻黄9g，甘草6g，生姜9g，石膏15g，杏仁9g，大枣6枚',
    instructions: '水煎服。',
  },

  // 五苓散系列（5个）
  五苓散: {
    formula: '五苓散',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病，发汗后，大汗出，胃中干，烦躁不得眠，欲得饮水者，少少与饮之，令胃气和则愈。若脉浮，小便不利，微热消渴者，五苓散主之。',
    keySymptoms: ['小便不利', '微热', '消渴', '脉浮', '水入即吐'],
    mechanism: '水湿内停，膀胱气化不利',
    treatmentMethod: '化饮',
    indications: ['太阳蓄水证', '水湿内停'],
    contraindications: ['阴虚小便不利'],
    dosage: '猪苓9g，茯苓9g，白术9g，泽泻15g，桂枝6g',
    instructions: '为散，每服6g，日三服，多饮暖水，汗出愈。',
  },
  猪苓汤: {
    formula: '猪苓汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '若脉浮发热，渴欲饮水，小便不利者，猪苓汤主之。',
    keySymptoms: ['小便不利', '发热', '渴欲饮水', '心烦不得眠'],
    mechanism: '水热互结，阴虚水停',
    treatmentMethod: '化饮',
    indications: ['阴虚水热互结', '小便不利'],
    contraindications: ['阳虚水肿'],
    dosage: '猪苓9g，茯苓9g，泽泻9g，阿胶9g，滑石9g',
    instructions: '水煎服。',
  },
  茯苓桂枝白术甘草汤: {
    formula: '茯苓桂枝白术甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒若吐若下后，心下逆满，气上冲胸，起则头眩，脉沉紧，发汗则动经，身为振振摇者，茯苓桂枝白术甘草汤主之。',
    keySymptoms: ['心下逆满', '气上冲胸', '起则头眩', '脉沉紧'],
    mechanism: '脾虚水停，中焦气滞',
    treatmentMethod: '化饮',
    indications: ['中焦水饮', '脾虚水停'],
    contraindications: ['湿热证'],
    dosage: '茯苓12g，桂枝9g，白术9g，炙甘草6g',
    instructions: '水煎服。',
  },
  茯苓桂枝甘草大枣汤: {
    formula: '茯苓桂枝甘草大枣汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '发汗后，其人脐下悸者，欲作奔豚，茯苓桂枝甘草大枣汤主之。',
    keySymptoms: ['脐下悸', '欲作奔豚', '心悸'],
    mechanism: '心阳虚，下焦水气上逆',
    treatmentMethod: '化饮',
    indications: ['心阳虚水气上逆', '脐下悸'],
    contraindications: ['肾阳虚水泛'],
    dosage: '茯苓15g，桂枝12g，炙甘草6g，大枣15枚',
    instructions: '水煎服，先煮茯苓。',
  },
  茯苓四逆汤: {
    formula: '茯苓四逆汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，二三日不已，至四五日，腹痛，小便不利，四肢沉重疼痛，自下利者，此为有水气。其人或咳，或小便利，或下利，或呕者，茯苓四逆汤主之。',
    keySymptoms: ['腹痛', '小便不利', '四肢沉重疼痛', '下利'],
    mechanism: '少阴阳虚，水气内停',
    treatmentMethod: '化饮',
    indications: ['少阴阳虚水停', '阳虚水肿'],
    contraindications: ['阴虚水肿'],
    dosage: '茯苓12g，人参6g，附子6g（生用），甘草6g，干姜6g',
    instructions: '水煎服。',
  },

  // 桃核承气汤系列（4个）
  桃核承气汤: {
    formula: '桃核承气汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病不解，热结膀胱，其人如狂，血自下，下者愈。其外不解者，尚未可攻，当先解其外。外解已，但少腹急结者，乃可攻之，宜桃核承气汤。',
    keySymptoms: ['少腹急结', '如狂', '小便自利', '脉沉结'],
    mechanism: '瘀热互结，蓄血下焦',
    treatmentMethod: '活血化瘀',
    indications: ['太阳蓄血证', '瘀热互结'],
    contraindications: ['表证未解', '孕妇'],
    dosage: '桃仁9g，大黄12g，桂枝6g，甘草6g，芒硝6g',
    instructions: '水煎服，先煮桃仁、桂枝、大黄，后纳芒硝。',
  },
  抵当汤: {
    formula: '抵当汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病六七日，表证仍在，脉微而沉，反不结胸，其人发狂者，以热在下焦，少腹当硬满，小便自利者，下血乃愈。所以然者，以太阳随经，瘀热在里故也。抵当汤主之。',
    keySymptoms: ['发狂', '少腹硬满', '小便自利', '脉沉结'],
    mechanism: '瘀血重证，热结下焦',
    treatmentMethod: '活血化瘀',
    indications: ['蓄血重证', '瘀血发狂'],
    contraindications: ['表证未解', '孕妇', '体虚者'],
    dosage: '水蛭9g，虻虫9g，桃仁9g，大黄15g',
    instructions: '水煎服。',
  },
  抵当丸: {
    formula: '抵当丸',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒有热，少腹满，应小便不利，今反利者，为有血也，当下之，不可余药，宜抵当丸。',
    keySymptoms: ['少腹满', '小便自利', '脉沉结'],
    mechanism: '瘀血内停，病势较缓',
    treatmentMethod: '活血化瘀',
    indications: ['蓄血轻证', '瘀血内停'],
    contraindications: ['表证未解', '孕妇'],
    dosage: '水蛭6g，虻虫6g，桃仁6g，大黄9g',
    instructions: '为丸，如大豆大，每服5丸，日三服。',
  },
  下瘀血汤: {
    formula: '下瘀血汤',
    source: '金匮要略',
    chapter: '妇人产后病篇',
    originalText: '产妇腹痛，法当以枳实芍药散，假令不愈者，此为腹中有干血着脐下，宜下瘀血汤主之。',
    keySymptoms: ['腹痛', '腹中有干血', '脐下痛'],
    mechanism: '产后瘀血内停',
    treatmentMethod: '活血化瘀',
    indications: ['产后腹痛', '瘀血内停'],
    contraindications: ['产后血虚腹痛'],
    dosage: '大黄6g，桃仁6g，蟅虫6g',
    instructions: '为末，酒煎顿服。',
  },

  // 其他太阳病方剂（15个）
  桂枝加大黄汤: {
    formula: '桂枝加大黄汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '本太阳病，医反下之，因而腹满时痛者，属太阴也，桂枝加芍药汤主之；大实痛者，桂枝加大黄汤主之。',
    keySymptoms: ['大实痛', '腹满', '发热', '恶风'],
    mechanism: '太阳病误下，表邪未解，兼阳明里实',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下大实痛', '表里同病'],
    contraindications: ['无里实的腹痛'],
    dosage: '桂枝9g，芍药18g，甘草6g，生姜9g，大枣12枚，大黄6g',
    instructions: '水煎服。',
  },
  桂枝加芍药汤: {
    formula: '桂枝加芍药汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '本太阳病，医反下之，因而腹满时痛者，属太阴也，桂枝加芍药汤主之。',
    keySymptoms: ['腹满时痛', '发热', '恶风', '汗出'],
    mechanism: '太阳病误下，损伤脾络',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下腹痛', '脾络不和'],
    contraindications: ['大实痛'],
    dosage: '桂枝9g，芍药18g，甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服。',
  },
  茯苓甘草汤: {
    formula: '茯苓甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒汗出而渴者，五苓散主之；不渴者，茯苓甘草汤主之。',
    keySymptoms: ['汗出', '不渴', '心下悸', '厥'],
    mechanism: '中焦水饮，胃气不和',
    treatmentMethod: '化饮',
    indications: ['中焦水饮', '胃气不和'],
    contraindications: ['阴虚汗出'],
    dosage: '茯苓6g，桂枝6g，甘草3g，生姜9g',
    instructions: '水煎服。',
  },
  甘草干姜汤: {
    formula: '甘草干姜汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '伤寒脉浮而自汗出，小便数，心烦，微恶寒，脚挛急，反与桂枝汤欲攻其表，此误也。得之便厥，咽中干，烦躁吐逆者，作甘草干姜汤与之，以复其阳。',
    keySymptoms: ['厥逆', '烦躁', '吐逆', '咽中干', '脚挛急'],
    mechanism: '阳虚不能温煦，阴液不能濡养',
    treatmentMethod: '温里',
    indications: ['阳虚厥逆', '中焦虚寒'],
    contraindications: ['热证厥逆'],
    dosage: '甘草12g，干姜6g',
    instructions: '水煎服。',
  },
  芍药甘草汤: {
    formula: '芍药甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '脚挛急，更作芍药甘草汤与之。',
    keySymptoms: ['脚挛急', '腹痛', '脉弦'],
    mechanism: '阴血亏虚，筋脉失养',
    treatmentMethod: '养血和血',
    indications: ['阴血亏虚挛急', '腹痛'],
    contraindications: ['阳虚挛急'],
    dosage: '芍药12g，甘草12g',
    instructions: '水煎服。',
  },
  芍药甘草附子汤: {
    formula: '芍药甘草附子汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '发汗病不解，反恶寒者，虚故也，芍药甘草附子汤主之。',
    keySymptoms: ['恶寒', '脚挛急', '脉微'],
    mechanism: '阴阳两虚，筋脉失养',
    treatmentMethod: '温经散寒',
    indications: ['阴阳两虚', '恶寒挛急'],
    contraindications: ['单纯阳虚或阴虚'],
    dosage: '芍药9g，甘草9g，附子6g（炮）',
    instructions: '水煎服。',
  },
  调胃承气汤: {
    formula: '调胃承气汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '太阳病三日，发汗不解，蒸蒸发热者，属胃也，调胃承气汤主之。',
    keySymptoms: ['蒸蒸发热', '腹胀满', '便秘', '谵语'],
    mechanism: '阳明燥热，腑气不通',
    treatmentMethod: '泻下',
    indications: ['阳明腑实证轻证', '燥热内结'],
    contraindications: ['表证未解', '体虚者'],
    dosage: '大黄12g，甘草6g，芒硝12g',
    instructions: '水煎服，先煮大黄、甘草，后纳芒硝。',
  },
  小承气汤: {
    formula: '小承气汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '阳明病，其人多汗，以津液外出，胃中燥，大便必硬，硬则谵语，小承气汤主之。',
    keySymptoms: ['大便秘结', '腹胀满', '谵语', '脉滑数'],
    mechanism: '阳明燥热，腑气不通',
    treatmentMethod: '泻下',
    indications: ['阳明腑实证', '燥热内结'],
    contraindications: ['表证未解', '体虚者'],
    dosage: '大黄12g，厚朴6g，枳实6g',
    instructions: '水煎服，先煮厚朴、枳实。',
  },
  大黄甘草汤: {
    formula: '大黄甘草汤',
    source: '金匮要略',
    chapter: '呕吐哕下利病篇',
    originalText: '食已即吐者，大黄甘草汤主之。',
    keySymptoms: ['食已即吐', '大便秘结', '胃热'],
    mechanism: '胃肠实热，腑气上逆',
    treatmentMethod: '泻下',
    indications: ['胃肠实热呕吐', '食已即吐'],
    contraindications: ['胃寒呕吐'],
    dosage: '大黄12g，甘草3g',
    instructions: '水煎服。',
  },
  甘草汤: {
    formula: '甘草汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，二三日，咽痛者，可与甘草汤。',
    keySymptoms: ['咽痛', '咽干', '脉细数'],
    mechanism: '热客咽喉，经脉不利',
    treatmentMethod: '清热',
    indications: ['少阴咽痛轻证', '热客咽喉'],
    contraindications: ['虚寒咽痛'],
    dosage: '甘草12g',
    instructions: '水煎服。',
  },
  桔梗汤: {
    formula: '桔梗汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，二三日，咽痛者，可与甘草汤；不瘥者，与桔梗汤。',
    keySymptoms: ['咽痛', '咳嗽', '咯痰不爽'],
    mechanism: '热客咽喉，肺气不宣',
    treatmentMethod: '清热',
    indications: ['少阴咽痛', '肺热咳嗽'],
    contraindications: ['虚寒咽痛'],
    dosage: '桔梗6g，甘草12g',
    instructions: '水煎服。',
  },
  半夏散及汤: {
    formula: '半夏散及汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，咽中痛，半夏散及汤主之。',
    keySymptoms: ['咽痛', '咽喉不利', '痰多'],
    mechanism: '寒客咽喉，痰气交阻',
    treatmentMethod: '温经散寒',
    indications: ['少阴寒客咽喉', '寒痰阻滞'],
    contraindications: ['热证咽痛'],
    dosage: '半夏6g，桂枝6g，甘草3g',
    instructions: '为散，每服3g，或水煎服。',
  },
  苦酒汤: {
    formula: '苦酒汤',
    source: '伤寒论',
    chapter: '太阳病篇',
    originalText: '少阴病，咽中伤，生疮，不能语言，声不出者，苦酒汤主之。',
    keySymptoms: ['咽中伤生疮', '不能语言', '声不出'],
    mechanism: '热客咽喉，经络损伤',
    treatmentMethod: '清热',
    indications: ['少阴咽疮', '咽喉溃烂'],
    contraindications: ['虚寒咽疮'],
    dosage: '半夏6g，鸡子清1个，苦酒（米醋）适量',
    instructions: '半夏、鸡子清、苦酒合煎，少少含咽。',
  },
};

// 导出所有太阳病方剂
export const getAllSunyangFormulas = (): FormulaEvidence[] => {
  return Object.values(SUNYANG_FORMULAS);
};

// ============================================
// 阳明病方剂（30个）
// ============================================

export const YANGMING_FORMULAS: Record<string, FormulaEvidence> = {
  // 白虎汤系列（6个）
  白虎汤: {
    formula: '白虎汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '三阳合病，腹满身重，难以转侧，口不仁，面垢，谵语，遗尿。发汗则谵语，下之则额上生汗，手足逆冷。若自汗出者，白虎汤主之。',
    keySymptoms: ['发热', '汗出', '口渴', '脉洪大', '烦渴'],
    mechanism: '阳明气分热盛，胃热津伤',
    treatmentMethod: '清热',
    indications: ['阳明气分热盛', '热盛伤津'],
    contraindications: ['表证未解', '无热而渴', '虚寒证'],
    dosage: '知母18g，石膏30-60g，甘草6g，粳米30g',
    instructions: '水煎服，先煮石膏、知母。',
  },
  白虎加人参汤: {
    formula: '白虎加人参汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '服桂枝汤后，大汗出，大烦渴不解，脉洪大者，白虎加人参汤主之。',
    keySymptoms: ['大烦渴', '大汗出', '脉洪大', '倦怠乏力'],
    mechanism: '阳明热盛，气津两伤',
    treatmentMethod: '清热',
    indications: ['阳明热盛气津两伤', '热盛耗气'],
    contraindications: ['表证未解', '无热虚证'],
    dosage: '知母18g，石膏30-60g，甘草6g，粳米30g，人参9g',
    instructions: '水煎服。',
  },
  白虎加桂枝汤: {
    formula: '白虎加桂枝汤',
    source: '金匮要略',
    chapter: '疟病篇',
    originalText: '温疟者，其脉如平，身无寒但热，骨节疼烦，时呕，白虎加桂枝汤主之。',
    keySymptoms: ['身无寒但热', '骨节疼烦', '时呕', '脉如平'],
    mechanism: '阳明热盛，兼有风湿',
    treatmentMethod: '清热',
    indications: ['温疟', '热盛兼风湿'],
    contraindications: ['寒疟', '虚疟'],
    dosage: '知母18g，石膏30g，甘草6g，粳米30g，桂枝9g',
    instructions: '水煎服。',
  },
  白虎加苍术汤: {
    formula: '白虎加苍术汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '湿温脉洪大，身重汗出，足冷，小便利，口中不仁，言语不利，白虎加苍术汤主之。',
    keySymptoms: ['身重', '汗出', '足冷', '小便利', '口中不仁'],
    mechanism: '阳明热盛，兼有湿邪',
    treatmentMethod: '清热燥湿',
    indications: ['湿温证', '热盛兼湿'],
    contraindications: ['单纯湿热无热'],
    dosage: '知母18g，石膏30g，甘草6g，粳米30g，苍术9g',
    instructions: '水煎服。',
  },
  竹叶石膏汤: {
    formula: '竹叶石膏汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒解后，虚羸少气，气逆欲吐，竹叶石膏汤主之。',
    keySymptoms: ['虚羸少气', '气逆欲吐', '烦渴', '舌红少苔'],
    mechanism: '余热未清，气津两伤',
    treatmentMethod: '养阴清热',
    indications: ['热病后期余热未清', '气津两伤'],
    contraindications: ['实热证', '寒证'],
    dosage: '竹叶12g，石膏30g，半夏9g，麦门冬15g，人参6g，甘草6g，粳米15g',
    instructions: '水煎服。',
  },
  栀子豉汤: {
    formula: '栀子豉汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '阳明病，脉浮而紧，咽燥口苦，腹满而喘，发热汗出，不恶寒，反恶热，身重。若发汗则躁，心愦愦，反谵语。若加温针，必怵惕烦躁不得眠。若下之，则胃中空虚，客气动膈，心中懊憹，舌上苔者，栀子豉汤主之。',
    keySymptoms: ['心中懊憹', '烦热', '失眠', '舌苔黄'],
    mechanism: '热扰胸膈，心中烦闷',
    treatmentMethod: '清热',
    indications: ['热扰胸膈', '心中懊憹'],
    contraindications: ['脾胃虚寒', '无热证'],
    dosage: '栀子9g，香豉9g',
    instructions: '水煎服。',
  },

  // 承气汤系列（5个）
  大承气汤: {
    formula: '大承气汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '阳明病，潮热，大便不通，腹大满不通者，可与大承气汤。',
    keySymptoms: ['潮热', '大便不通', '腹大满痛', '谵语', '脉沉实有力'],
    mechanism: '阳明燥热，腑气不通',
    treatmentMethod: '泻下',
    indications: ['阳明腑实证', '燥热内结'],
    contraindications: ['表证未解', '体虚者', '孕妇'],
    dosage: '大黄12g（酒洗），厚朴12g，枳实12g，芒硝9g',
    instructions: '先煮厚朴、枳实，后纳大黄，最后纳芒硝。',
  },
  大承气汤变方: {
    formula: '大承气汤变方',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '二阳并病，太阳证罢，但发潮热，手足漐漐汗出，大便难而谵语者，下之则愈，宜大承气汤。',
    keySymptoms: ['潮热', '手足漐漐汗出', '大便难', '谵语'],
    mechanism: '阳明燥热，腑气不通',
    treatmentMethod: '泻下',
    indications: ['阳明腑实证', '二阳并病转属阳明'],
    contraindications: ['表证未解', '体虚者'],
    dosage: '大黄12g，厚朴12g，枳实12g，芒硝9g',
    instructions: '同大承气汤。',
  },
  麻子仁丸: {
    formula: '麻子仁丸',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '趺阳脉浮而涩，浮则胃气强，涩则小便数，浮涩相搏，大便则硬，其脾为约，麻子仁丸主之。',
    keySymptoms: ['大便干结', '小便频数', '脉浮涩'],
    mechanism: '胃强脾弱，津液偏渗',
    treatmentMethod: '泻下',
    indications: ['脾约证', '胃强脾弱便秘'],
    contraindications: ['实热便秘', '孕妇'],
    dosage: '麻子仁15g，芍药9g，枳实6g，大黄6g，厚朴6g，杏仁6g',
    instructions: '为丸，如梧桐子大，每服10丸，日三服。',
  },
  蜜煎导: {
    formula: '蜜煎导',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '阳明病，自汗出，若发汗，小便自利者，此为津液内竭，虽硬不可攻之，当须自欲大便，宜蜜煎导而通之。',
    keySymptoms: ['大便干结', '小便自利', '自汗出'],
    mechanism: '津液内竭，肠道失润',
    treatmentMethod: '泻下',
    indications: ['津亏便秘', '津液内竭'],
    contraindications: ['实热便秘'],
    dosage: '食蜜适量',
    instructions: '将食蜜熬制成栓状，纳入肛门。',
  },
  土瓜根导: {
    formula: '土瓜根导',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '若土瓜根及大猪胆汁，皆可为导。',
    keySymptoms: ['大便干结', '小便自利'],
    mechanism: '津液内竭，肠道失润',
    treatmentMethod: '泻下',
    indications: ['津亏便秘'],
    contraindications: ['实热便秘'],
    dosage: '土瓜根适量',
    instructions: '为末，醋调和，纳入肛门。',
  },

  // 泻心汤系列（6个）
  大黄黄连泻心汤: {
    formula: '大黄黄连泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '心下痞，按之濡，其脉关上浮者，大黄黄连泻心汤主之。',
    keySymptoms: ['心下痞', '按之濡', '脉关上浮'],
    mechanism: '胃热气滞，心下痞满',
    treatmentMethod: '清热',
    indications: ['胃热痞证', '热痞'],
    contraindications: ['脾胃虚寒痞证'],
    dosage: '大黄6g，黄连3g',
    instructions: '麻沸汤渍之，须臾绞去滓，分温再服。',
  },
  附子泻心汤: {
    formula: '附子泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '心下痞，而复恶寒汗出者，附子泻心汤主之。',
    keySymptoms: ['心下痞', '恶寒汗出', '脉沉'],
    mechanism: '热结心下，兼肾阳虚',
    treatmentMethod: '温里',
    indications: ['热痞兼阳虚', '胃热肾寒'],
    contraindications: ['单纯热痞'],
    dosage: '大黄6g，黄连3g，黄芩3g，附子6g（炮，别煮取汁）',
    instructions: '三黄麻沸汤渍，附子另煮取汁，合和服。',
  },
  半夏泻心汤: {
    formula: '半夏泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '但满而不痛者，此为痞，半夏泻心汤主之。',
    keySymptoms: ['心下痞满', '呕吐', '肠鸣', '舌苔黄腻'],
    mechanism: '寒热互结，脾胃不和',
    treatmentMethod: '和解少阳',
    indications: ['寒热互结痞证', '脾胃不和'],
    contraindications: ['单纯热痞或寒痞'],
    dosage: '半夏9g，黄芩6g，干姜6g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  生姜泻心汤: {
    formula: '生姜泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒汗出解之后，胃中不和，心下痞硬，干噫食臭，胁下有水气，腹中雷鸣，下利者，生姜泻心汤主之。',
    keySymptoms: ['心下痞硬', '干噫食臭', '腹中雷鸣', '下利'],
    mechanism: '水饮内停，胃失和降',
    treatmentMethod: '和解少阳',
    indications: ['水饮痞证', '胃失和降'],
    contraindications: ['无水饮痞证'],
    dosage: '生姜12g，半夏9g，黄芩6g，干姜3g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  甘草泻心汤: {
    formula: '甘草泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒中风，医反下之，其人下利日数十行，谷不化，腹中雷鸣，心下痞硬而满，干呕心烦不得安。医见心下痞，谓病不尽，复下之，其痞益甚，此非结热，但以胃中虚，客气上逆，故使硬也，甘草泻心汤主之。',
    keySymptoms: ['心下痞硬', '下利日数十行', '腹中雷鸣', '心烦不得安'],
    mechanism: '脾胃虚弱，客气上逆',
    treatmentMethod: '调和脾胃',
    indications: ['脾胃虚弱痞证', '虚痞'],
    contraindications: ['实痞'],
    dosage: '甘草12g，半夏9g，黄芩6g，干姜6g，人参6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  黄连泻心汤: {
    formula: '黄连泻心汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '心下痞，按之濡，其脉关上浮者，大黄黄连泻心汤主之。',
    keySymptoms: ['心下痞', '按之濡', '脉关上浮'],
    mechanism: '胃热气滞，心下痞满',
    treatmentMethod: '清热',
    indications: ['胃热痞证', '热痞'],
    contraindications: ['脾胃虚寒痞证'],
    dosage: '黄连6g',
    instructions: '水煎服。',
  },

  // 其他阳明病方剂（13个）
  栀子厚朴汤: {
    formula: '栀子厚朴汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒下后，心烦腹满，卧起不安者，栀子厚朴汤主之。',
    keySymptoms: ['心烦', '腹满', '卧起不安', '舌苔黄'],
    mechanism: '热扰胸膈，腑气不通',
    treatmentMethod: '清热',
    indications: ['热扰胸膈兼腹满', '心烦腹满'],
    contraindications: ['寒证腹满'],
    dosage: '栀子9g，厚朴12g，枳实6g',
    instructions: '水煎服。',
  },
  栀子干姜汤: {
    formula: '栀子干姜汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒，医以丸药大下之，身热不去，微烦者，栀子干姜汤主之。',
    keySymptoms: ['身热不去', '微烦', '腹痛', '便溏'],
    mechanism: '上热下寒，寒热错杂',
    treatmentMethod: '清上温下',
    indications: ['上热下寒', '寒热错杂'],
    contraindications: ['单纯热证或寒证'],
    dosage: '栀子9g，干姜6g',
    instructions: '水煎服。',
  },
  栀子柏皮汤: {
    formula: '栀子柏皮汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒身黄，发热，栀子柏皮汤主之。',
    keySymptoms: ['身黄', '发热', '小便不利', '舌苔黄'],
    mechanism: '湿热郁蒸，胆汁外溢',
    treatmentMethod: '清热',
    indications: ['湿热发黄', '阳黄'],
    contraindications: ['寒湿发黄'],
    dosage: '栀子9g，甘草6g，黄柏6g',
    instructions: '水煎服。',
  },
  茵陈蒿汤: {
    formula: '茵陈蒿汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '阳明病，发热汗出者，此为热越，不能发黄也。但头汗出，身无汗，齐颈而还，小便不利，渴引水浆者，此为瘀热在里，身必发黄，茵陈蒿汤主之。',
    keySymptoms: ['身黄', '头汗出', '小便不利', '渴引水浆', '便秘'],
    mechanism: '湿热郁蒸，胆汁外溢',
    treatmentMethod: '清热',
    indications: ['湿热发黄', '阳黄'],
    contraindications: ['寒湿发黄'],
    dosage: '茵陈18g，栀子9g，大黄6g',
    instructions: '水煎服，先煮茵陈。',
  },
  茵陈五苓散: {
    formula: '茵陈五苓散',
    source: '金匮要略',
    chapter: '黄疸病篇',
    originalText: '黄疸病，茵陈五苓散主之。',
    keySymptoms: ['身黄', '小便不利', '微热', '口渴'],
    mechanism: '湿热内停，膀胱气化不利',
    treatmentMethod: '化饮',
    indications: ['湿热发黄', '阳黄轻证'],
    contraindications: ['寒湿发黄'],
    dosage: '茵陈15g，五苓散15g',
    instructions: '为散，每服6g，日三服。',
  },
  大柴胡汤: {
    formula: '大柴胡汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '太阳病，过经十余日，反二三下之，后四五日，柴胡证仍在者，先与小柴胡汤。呕不止，心下急，郁郁微烦者，为未解也，与大柴胡汤，下之则愈。',
    keySymptoms: ['呕不止', '心下急', '郁郁微烦', '便秘', '脉弦有力'],
    mechanism: '少阳兼阳明里实',
    treatmentMethod: '和解少阳',
    indications: ['少阳兼阳明里实', '少阳证兼便秘'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡12g，黄芩9g，芍药9g，半夏9g，生姜12g，枳实6g，大枣4枚，大黄6g',
    instructions: '水煎服。',
  },
  柴胡加芒硝汤: {
    formula: '柴胡加芒硝汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒十三日不解，胸胁满而呕，日晡所发潮热，已而微利，此本柴胡证，下之以不得利，今反利者，知医以丸药下之，此非其治也。潮热者，实也，先宜服小柴胡汤以解外，后以柴胡加芒硝汤主之。',
    keySymptoms: ['胸胁满而呕', '日晡潮热', '微利', '脉弦'],
    mechanism: '少阳兼阳明里实轻证',
    treatmentMethod: '和解少阳',
    indications: ['少阳兼阳明里实轻证', '胸胁满兼潮热'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡8g，黄芩3g，人参3g，甘草3g，生姜3g，半夏4g，大枣2枚，芒硝6g',
    instructions: '水煎服，先煮诸药，后纳芒硝。',
  },
  厚朴生姜半夏甘草人参汤: {
    formula: '厚朴生姜半夏甘草人参汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '发汗后，腹胀满者，厚朴生姜半夏甘草人参汤主之。',
    keySymptoms: ['腹胀满', '食后尤甚', '脉缓'],
    mechanism: '脾虚气滞，运化失司',
    treatmentMethod: '调和脾胃',
    indications: ['脾虚腹胀', '腹胀满'],
    contraindications: ['实热腹胀'],
    dosage: '厚朴12g，生姜9g，半夏9g，甘草6g，人参3g',
    instructions: '水煎服。',
  },
  桂枝加大黄汤2: {
    formula: '桂枝加大黄汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '本太阳病，医反下之，因而腹满时痛者，属太阴也，桂枝加芍药汤主之；大实痛者，桂枝加大黄汤主之。',
    keySymptoms: ['大实痛', '腹满', '发热', '恶风'],
    mechanism: '太阳病误下，表邪未解，兼阳明里实',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下大实痛', '表里同病'],
    contraindications: ['无里实的腹痛'],
    dosage: '桂枝9g，芍药18g，甘草6g，生姜9g，大枣12枚，大黄6g',
    instructions: '水煎服。',
  },
  茯苓桂枝白术甘草汤2: {
    formula: '茯苓桂枝白术甘草汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒若吐若下后，心下逆满，气上冲胸，起则头眩，脉沉紧，发汗则动经，身为振振摇者，茯苓桂枝白术甘草汤主之。',
    keySymptoms: ['心下逆满', '气上冲胸', '起则头眩', '脉沉紧'],
    mechanism: '脾虚水停，中焦气滞',
    treatmentMethod: '化饮',
    indications: ['中焦水饮', '脾虚水停'],
    contraindications: ['湿热证'],
    dosage: '茯苓12g，桂枝9g，白术9g，炙甘草6g',
    instructions: '水煎服。',
  },
  吴茱萸汤: {
    formula: '吴茱萸汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '食谷欲呕，属阳明也，吴茱萸汤主之。',
    keySymptoms: ['食谷欲呕', '干呕吐涎沫', '头痛', '四肢厥冷'],
    mechanism: '中焦虚寒，胃气上逆',
    treatmentMethod: '温里',
    indications: ['中焦虚寒呕吐', '胃寒呕吐'],
    contraindications: ['胃热呕吐'],
    dosage: '吴茱萸9g，人参9g，生姜18g，大枣4枚',
    instructions: '水煎服。',
  },
  小建中汤: {
    formula: '小建中汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '伤寒二三日，心中悸而烦者，小建中汤主之。',
    keySymptoms: ['心中悸', '烦', '腹中急痛', '面色无华'],
    mechanism: '中焦虚寒，气血不足',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '水煎服，去滓，内胶饴，更上微火消解。',
  },
  黄芩汤: {
    formula: '黄芩汤',
    source: '伤寒论',
    chapter: '阳明病篇',
    originalText: '太阳与少阳合病，自下利者，与黄芩汤；若呕者，黄芩加半夏生姜汤主之。',
    keySymptoms: ['下利', '发热', '口苦', '腹痛'],
    mechanism: '少阳邪热内迫肠道',
    treatmentMethod: '清热',
    indications: ['少阳热利', '热性下利'],
    contraindications: ['虚寒下利'],
    dosage: '黄芩9g，芍药6g，甘草6g，大枣4枚',
    instructions: '水煎服。',
  },
};

// 导出所有阳明病方剂
export const getAllYangmingFormulas = (): FormulaEvidence[] => {
  return Object.values(YANGMING_FORMULAS);
};

// ============================================
// 少阳病方剂（20个）
// ============================================

export const SHAOYANG_FORMULAS: Record<string, FormulaEvidence> = {
  // 小柴胡汤系列（10个）
  小柴胡汤: {
    formula: '小柴胡汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '少阳之为病，口苦、咽干、目眩也。伤寒五六日，中风，往来寒热，胸胁苦满，嘿嘿不欲饮食，心烦喜呕，或胸中烦而不呕，或渴，或腹中痛，或胁下痞硬，或心下悸、小便不利，或不渴、身有微热，或咳者，小柴胡汤主之。',
    keySymptoms: ['往来寒热', '胸胁苦满', '嘿嘿不欲饮食', '心烦喜呕', '口苦', '咽干', '目眩', '脉弦'],
    mechanism: '邪犯少阳，枢机不利',
    treatmentMethod: '和解少阳',
    indications: ['少阳病', '邪犯少阳'],
    contraindications: ['表证未解', '里实热证'],
    dosage: '柴胡12g，黄芩9g，人参6g，半夏9g，甘草6g，生姜9g，大枣4枚',
    instructions: '水煎服，去滓再煎，温服。',
  },
  小柴胡汤变方1: {
    formula: '小柴胡汤变方1',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '血弱气尽，腠理开，邪气因入，与正气相搏，结于胁下。正邪纷争，往来寒热，休作有时，嘿嘿不欲饮食，脏腑相连，其痛必下，邪高痛下，故使呕也，小柴胡汤主之。',
    keySymptoms: ['往来寒热', '胸胁苦满', '嘿嘿不欲饮食', '心烦喜呕', '脉弦'],
    mechanism: '邪犯少阳，枢机不利',
    treatmentMethod: '和解少阳',
    indications: ['少阳病', '邪犯少阳'],
    contraindications: ['表证未解', '里实热证'],
    dosage: '柴胡12g，黄芩9g，人参6g，半夏9g，甘草6g，生姜9g，大枣4枚',
    instructions: '水煎服。',
  },
  小柴胡汤变方2: {
    formula: '小柴胡汤变方2',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒四五日，身热恶风，颈项强，胁下满，手足温而渴者，小柴胡汤主之。',
    keySymptoms: ['身热', '恶风', '颈项强', '胁下满', '手足温而渴', '脉弦'],
    mechanism: '三阳合病，邪在少阳',
    treatmentMethod: '和解少阳',
    indications: ['三阳合病', '邪在少阳'],
    contraindications: ['表证未解', '里实热证'],
    dosage: '柴胡12g，黄芩9g，人参6g，半夏9g，甘草6g，生姜9g，大枣4枚',
    instructions: '水煎服。',
  },
  小柴胡汤加减1: {
    formula: '小柴胡汤加减1',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '若胸中烦而不呕者，去半夏、人参，加栝楼实一枚。若渴，去半夏，加人参合前成四两半，栝楼根四两。若腹中痛者，去黄芩，加芍药三两。若胁下痞硬，去大枣，加牡蛎四两。若心下悸，小便不利者，去黄芩，加茯苓四两。若不渴，外有微热者，去人参，加桂枝三两，温覆微汗愈。若咳者，去人参、大枣、生姜，加五味子半升、干姜二两。',
    keySymptoms: ['胸中烦而不呕', '胸中烦', '口渴', '腹中痛', '胁下痞硬', '心下悸', '小便不利', '不渴外有微热', '咳嗽'],
    mechanism: '邪犯少阳，兼见不同证候',
    treatmentMethod: '和解少阳',
    indications: ['少阳病兼证'],
    contraindications: ['根据具体兼证而定'],
    dosage: '柴胡12g，黄芩9g，人参6g，半夏9g，甘草6g，生姜9g，大枣4枚（根据兼证加减）',
    instructions: '水煎服。',
  },
  柴胡桂枝汤: {
    formula: '柴胡桂枝汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒六七日，发热微恶寒，支节烦疼，微呕，心下支结，外证未去者，柴胡桂枝汤主之。',
    keySymptoms: ['发热微恶寒', '支节烦疼', '微呕', '心下支结', '脉浮弦'],
    mechanism: '太阳少阳合病',
    treatmentMethod: '和解少阳',
    indications: ['太阳少阳合病', '发热支节烦疼'],
    contraindications: ['单纯太阳证或少阳证'],
    dosage: '柴胡12g，黄芩4.5g，人参4.5g，半夏4.5g，甘草3g，生姜4.5g，大枣2枚，芍药4.5g，桂枝4.5g',
    instructions: '水煎服。',
  },
  柴胡桂枝干姜汤: {
    formula: '柴胡桂枝干姜汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒五六日，已发汗而复下之，胸胁满微结，小便不利，渴而不呕，但头汗出，往来寒热，心烦者，此为未解也，柴胡桂枝干姜汤主之。',
    keySymptoms: ['胸胁满微结', '小便不利', '渴而不呕', '头汗出', '往来寒热', '心烦', '脉弦'],
    mechanism: '少阳病兼水饮内停',
    treatmentMethod: '和解少阳',
    indications: ['少阳病兼水饮', '胸胁满小便不利'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡12g，桂枝6g，干姜6g，栝楼根12g，黄芩4.5g，牡蛎6g，甘草3g',
    instructions: '水煎服。',
  },
  柴胡加龙骨牡蛎汤: {
    formula: '柴胡加龙骨牡蛎汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒八九日，下之，胸满烦惊，小便不利，谵语，一身尽重，不可转侧者，柴胡加龙骨牡蛎汤主之。',
    keySymptoms: ['胸满烦惊', '小便不利', '谵语', '一身尽重', '不可转侧', '脉弦'],
    mechanism: '少阳病兼痰热扰心',
    treatmentMethod: '和解少阳',
    indications: ['少阳病兼痰热', '胸满烦惊'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡12g，龙骨4.5g，黄芩4.5g，生姜4.5g，铅丹1.5g，人参4.5g，桂枝4.5g，茯苓4.5g，半夏4.5g，大黄6g，牡蛎4.5g，大枣2枚',
    instructions: '水煎服。',
  },
  四逆散: {
    formula: '四逆散',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '少阴病，四逆，其人或咳，或悸，或小便不利，或腹中痛，或泄利下重者，四逆散主之。',
    keySymptoms: ['四逆', '咳', '悸', '小便不利', '腹中痛', '泄利下重', '脉弦'],
    mechanism: '肝胃不和，阳气内郁',
    treatmentMethod: '疏肝和胃',
    indications: ['肝胃不和', '阳气内郁'],
    contraindications: ['阳虚四逆'],
    dosage: '柴胡6g，芍药6g，枳实6g，甘草6g',
    instructions: '为散，每服6g，或水煎服。',
  },
  逍遥散: {
    formula: '逍遥散',
    source: '太平惠民和剂局方',
    chapter: '妇科方剂',
    originalText: '治血虚劳倦，五心烦热，肢体疼痛，头目昏重，心悸颊赤，口燥咽干，发热盗汗，减食嗜卧，及血热相搏，月水不调，脐腹胀痛，寒热如疟，又疗室女血弱阴虚，荣卫不和，痰嗽潮热，肌体羸瘦，渐成骨蒸。',
    keySymptoms: ['两胁作痛', '头痛目眩', '口燥咽干', '神疲食少', '月经不调', '乳房胀痛', '脉弦而虚'],
    mechanism: '肝郁血虚，脾弱不运',
    treatmentMethod: '疏肝解郁',
    indications: ['肝郁血虚脾弱', '月经不调'],
    contraindications: ['肝火炽盛'],
    dosage: '柴胡9g，当归9g，白芍9g，白术9g，茯苓9g，甘草4.5g，薄荷3g，煨生姜3g',
    instructions: '为散，每服6-9g，或水煎服。',
  },
  丹栀逍遥散: {
    formula: '丹栀逍遥散',
    source: '内科摘要',
    chapter: '肝脾不和方剂',
    originalText: '治肝脾血虚，化火生热，或烦躁易怒，或自汗盗汗，或头痛目涩，或颊赤口干，或月经不调，或少腹作痛，或小腹胀坠。',
    keySymptoms: ['烦躁易怒', '自汗盗汗', '头痛目涩', '颊赤口干', '月经不调', '少腹作痛', '脉弦数'],
    mechanism: '肝郁血虚化火',
    treatmentMethod: '疏肝解郁',
    indications: ['肝郁化火', '血虚有热'],
    contraindications: ['肝脾虚寒'],
    dosage: '柴胡9g，当归9g，白芍9g，白术9g，茯苓9g，甘草4.5g，薄荷3g，煨生姜3g，牡丹皮9g，栀子9g',
    instructions: '水煎服。',
  },

  // 大柴胡汤系列（3个）
  大柴胡汤2: {
    formula: '大柴胡汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '太阳病，过经十余日，反二三下之，后四五日，柴胡证仍在者，先与小柴胡汤。呕不止，心下急，郁郁微烦者，为未解也，与大柴胡汤，下之则愈。',
    keySymptoms: ['呕不止', '心下急', '郁郁微烦', '便秘', '脉弦有力'],
    mechanism: '少阳兼阳明里实',
    treatmentMethod: '和解少阳',
    indications: ['少阳兼阳明里实', '少阳证兼便秘'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡12g，黄芩9g，芍药9g，半夏9g，生姜12g，枳实6g，大枣4枚，大黄6g',
    instructions: '水煎服。',
  },
  大柴胡汤变方1: {
    formula: '大柴胡汤变方1',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒发热，汗出不解，心中痞硬，呕吐而下利者，大柴胡汤主之。',
    keySymptoms: ['发热', '心中痞硬', '呕吐', '下利', '脉弦有力'],
    mechanism: '少阳兼阳明里实',
    treatmentMethod: '和解少阳',
    indications: ['少阳兼阳明里实', '发热痞硬呕吐下利'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡12g，黄芩9g，芍药9g，半夏9g，生姜12g，枳实6g，大枣4枚，大黄6g',
    instructions: '水煎服。',
  },
  柴胡加芒硝汤2: {
    formula: '柴胡加芒硝汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒十三日不解，胸胁满而呕，日晡所发潮热，已而微利，此本柴胡证，下之以不得利，今反利者，知医以丸药下之，此非其治也。潮热者，实也，先宜服小柴胡汤以解外，后以柴胡加芒硝汤主之。',
    keySymptoms: ['胸胁满而呕', '日晡潮热', '微利', '脉弦'],
    mechanism: '少阳兼阳明里实轻证',
    treatmentMethod: '和解少阳',
    indications: ['少阳兼阳明里实轻证', '胸胁满兼潮热'],
    contraindications: ['单纯少阳证'],
    dosage: '柴胡8g，黄芩3g，人参3g，甘草3g，生姜3g，半夏4g，大枣2枚，芒硝6g',
    instructions: '水煎服，先煮诸药，后纳芒硝。',
  },

  // 其他少阳病方剂（7个）
  黄芩加半夏生姜汤: {
    formula: '黄芩加半夏生姜汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '太阳与少阳合病，自下利者，与黄芩汤；若呕者，黄芩加半夏生姜汤主之。',
    keySymptoms: ['下利', '呕吐', '发热', '口苦', '脉弦数'],
    mechanism: '少阳邪热内迫肠道，胃气上逆',
    treatmentMethod: '和解少阳',
    indications: ['少阳热利兼呕', '少阳兼呕'],
    contraindications: ['虚寒下利'],
    dosage: '黄芩9g，芍药6g，甘草6g，大枣4枚，半夏9g，生姜9g',
    instructions: '水煎服。',
  },
  半夏泻心汤2: {
    formula: '半夏泻心汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '但满而不痛者，此为痞，半夏泻心汤主之。',
    keySymptoms: ['心下痞满', '呕吐', '肠鸣', '舌苔黄腻', '脉弦'],
    mechanism: '寒热互结，脾胃不和',
    treatmentMethod: '和解少阳',
    indications: ['寒热互结痞证', '脾胃不和'],
    contraindications: ['单纯热痞或寒痞'],
    dosage: '半夏9g，黄芩6g，干姜6g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  生姜泻心汤2: {
    formula: '生姜泻心汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒汗出解之后，胃中不和，心下痞硬，干噫食臭，胁下有水气，腹中雷鸣，下利者，生姜泻心汤主之。',
    keySymptoms: ['心下痞硬', '干噫食臭', '腹中雷鸣', '下利', '脉弦'],
    mechanism: '水饮内停，胃失和降',
    treatmentMethod: '和解少阳',
    indications: ['水饮痞证', '胃失和降'],
    contraindications: ['无水饮痞证'],
    dosage: '生姜12g，半夏9g，黄芩6g，干姜3g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  甘草泻心汤2: {
    formula: '甘草泻心汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒中风，医反下之，其人下利日数十行，谷不化，腹中雷鸣，心下痞硬而满，干呕心烦不得安。医见心下痞，谓病不尽，复下之，其痞益甚，此非结热，但以胃中虚，客气上逆，故使硬也，甘草泻心汤主之。',
    keySymptoms: ['心下痞硬', '下利日数十行', '腹中雷鸣', '心烦不得安', '脉弦'],
    mechanism: '脾胃虚弱，客气上逆',
    treatmentMethod: '调和脾胃',
    indications: ['脾胃虚弱痞证', '虚痞'],
    contraindications: ['实痞'],
    dosage: '甘草12g，半夏9g，黄芩6g，干姜6g，人参6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  干姜黄芩黄连人参汤: {
    formula: '干姜黄芩黄连人参汤',
    source: '伤寒论',
    chapter: '少阳病篇',
    originalText: '伤寒本自寒下，医复吐下之，寒格更逆吐下，若食入口即吐，干姜黄芩黄连人参汤主之。',
    keySymptoms: ['食入口即吐', '下利', '脉弦'],
    mechanism: '上热下寒，寒热格拒',
    treatmentMethod: '清上温下',
    indications: ['上热下寒', '寒热格拒'],
    contraindications: ['单纯热证或寒证'],
    dosage: '干姜6g，黄芩6g，黄连3g，人参6g',
    instructions: '水煎服。',
  },
  乌梅丸: {
    formula: '乌梅丸',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '蛔厥者，其人当吐蛔，今病者静，而复时烦者，此为脏寒，蛔上入其膈，故烦，须臾复止，得食而呕又烦者，蛔闻食臭出，其人常自吐蛔。蛔厥者，乌梅丸主之。又主久利。',
    keySymptoms: ['烦闷', '时静时烦', '得食而呕又烦', '常自吐蛔', '手足厥冷', '腹痛时作'],
    mechanism: '脏寒蛔动，寒热错杂',
    treatmentMethod: '清上温下',
    indications: ['蛔厥', '久利', '寒热错杂'],
    contraindications: ['单纯寒证或热证'],
    dosage: '乌梅15g，细辛3g，干姜6g，黄连6g，当归6g，附子6g（炮），蜀椒6g，桂枝6g，人参6g，黄柏6g',
    instructions: '为丸，如梧桐子大，每服10丸，日三服。',
  },
  柴胡去半夏加栝楼根汤: {
    formula: '柴胡去半夏加栝楼根汤',
    source: '金匮要略',
    chapter: '疟病篇',
    originalText: '疟病发渴者，柴胡去半夏加栝楼根汤主之。',
    keySymptoms: ['疟病', '发渴', '往来寒热', '脉弦'],
    mechanism: '少阳病兼津伤',
    treatmentMethod: '和解少阳',
    indications: ['少阳疟病发渴', '少阳病津伤'],
    contraindications: ['单纯少阳证无渴'],
    dosage: '柴胡12g，人参6g，黄芩9g，甘草6g，生姜9g，大枣4枚，栝楼根12g',
    instructions: '水煎服。',
  },
};

// 导出所有少阳病方剂
export const getAllShaoyangFormulas = (): FormulaEvidence[] => {
  return Object.values(SHAOYANG_FORMULAS);
};

// ============================================
// 太阴病方剂（20个）
// ============================================

export const TAIYIN_FORMULAS: Record<string, FormulaEvidence> = {
  // 理中汤系列（8个）
  理中丸: {
    formula: '理中丸',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。若下之，必胸下结硬。',
    keySymptoms: ['腹满', '呕吐', '食不下', '自利', '时腹自痛', '口不渴', '脉沉缓'],
    mechanism: '脾胃虚寒，运化失司',
    treatmentMethod: '温中健脾',
    indications: ['太阴病', '脾胃虚寒'],
    contraindications: ['脾胃湿热', '阳明腑实'],
    dosage: '人参9g，白术9g，干姜9g，甘草9g',
    instructions: '为丸，如鸡子黄大，每服1丸，日三服。',
  },
  理中汤: {
    formula: '理中汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '霍乱，头痛发热，身疼痛，热多欲饮水者，五苓散主之；寒多不用水者，理中丸主之。',
    keySymptoms: ['霍乱', '吐利交作', '腹中冷痛', '口不渴', '脉沉迟'],
    mechanism: '脾胃虚寒，升降失司',
    treatmentMethod: '温中健脾',
    indications: ['脾胃虚寒吐利', '霍乱寒证'],
    contraindications: ['脾胃湿热吐利'],
    dosage: '人参9g，白术9g，干姜9g，甘草9g',
    instructions: '水煎服。',
  },
  附子理中丸: {
    formula: '附子理中丸',
    source: '太平惠民和剂局方',
    chapter: '脾胃方剂',
    originalText: '治脾胃冷弱，心腹绞痛，呕吐泄利，霍乱转筋，体冷微汗，手足厥寒，心下逆满，腹中雷鸣，饮食不进，及一切沉寒痼冷。',
    keySymptoms: ['心腹绞痛', '呕吐泄利', '霍乱转筋', '体冷微汗', '手足厥寒', '脉沉微'],
    mechanism: '脾肾阳虚，阴寒内盛',
    treatmentMethod: '温中健脾',
    indications: ['脾肾阳虚', '阴寒内盛'],
    contraindications: ['阴虚火旺'],
    dosage: '附子6g（炮），人参6g，白术9g，干姜6g，甘草6g',
    instructions: '为丸，每服9g，日二服。',
  },
  桂枝人参汤2: {
    formula: '桂枝人参汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '太阳病，外证未除，而数下之，遂协热而利，利下不止，心下痞硬，表里不解者，桂枝人参汤主之。',
    keySymptoms: ['利下不止', '心下痞硬', '发热', '恶风', '脉浮而缓'],
    mechanism: '表证未解，脾胃虚寒，协热下利',
    treatmentMethod: '调和营卫',
    indications: ['表里不解下利', '脾胃虚寒下利'],
    contraindications: ['热性下利'],
    dosage: '桂枝12g，炙甘草12g，白术9g，人参9g，干姜9g',
    instructions: '水煎服。',
  },
  桂枝加芍药汤2: {
    formula: '桂枝加芍药汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '本太阳病，医反下之，因而腹满时痛者，属太阴也，桂枝加芍药汤主之。',
    keySymptoms: ['腹满时痛', '发热', '恶风', '汗出', '脉浮缓'],
    mechanism: '太阳病误下，损伤脾络',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下腹痛', '脾络不和'],
    contraindications: ['大实痛'],
    dosage: '桂枝9g，芍药18g，甘草6g，生姜9g，大枣12枚',
    instructions: '水煎服。',
  },
  桂枝加大黄汤3: {
    formula: '桂枝加大黄汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '本太阳病，医反下之，因而腹满时痛者，属太阴也，桂枝加芍药汤主之；大实痛者，桂枝加大黄汤主之。',
    keySymptoms: ['大实痛', '腹满', '发热', '恶风', '脉沉有力'],
    mechanism: '太阳病误下，表邪未解，兼阳明里实',
    treatmentMethod: '调和营卫',
    indications: ['太阳病误下大实痛', '表里同病'],
    contraindications: ['无里实的腹痛'],
    dosage: '桂枝9g，芍药18g，甘草6g，生姜9g，大枣12枚，大黄6g',
    instructions: '水煎服。',
  },
  厚朴生姜半夏甘草人参汤2: {
    formula: '厚朴生姜半夏甘草人参汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '发汗后，腹胀满者，厚朴生姜半夏甘草人参汤主之。',
    keySymptoms: ['腹胀满', '食后尤甚', '脉缓', '舌淡苔白'],
    mechanism: '脾虚气滞，运化失司',
    treatmentMethod: '调和脾胃',
    indications: ['脾虚腹胀', '腹胀满'],
    contraindications: ['实热腹胀'],
    dosage: '厚朴12g，生姜9g，半夏9g，甘草6g，人参3g',
    instructions: '水煎服。',
  },
  吴茱萸汤2: {
    formula: '吴茱萸汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '食谷欲呕，属阳明也，吴茱萸汤主之。',
    keySymptoms: ['食谷欲呕', '干呕吐涎沫', '头痛', '四肢厥冷', '脉沉迟'],
    mechanism: '中焦虚寒，胃气上逆',
    treatmentMethod: '温里',
    indications: ['中焦虚寒呕吐', '胃寒呕吐'],
    contraindications: ['胃热呕吐'],
    dosage: '吴茱萸9g，人参9g，生姜18g，大枣4枚',
    instructions: '水煎服。',
  },

  // 建中汤系列（6个）
  小建中汤2: {
    formula: '小建中汤',
    source: '伤寒论',
    chapter: '太阴病篇',
    originalText: '伤寒二三日，心中悸而烦者，小建中汤主之。',
    keySymptoms: ['心中悸', '烦', '腹中急痛', '面色无华', '脉细涩'],
    mechanism: '中焦虚寒，气血不足',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '水煎服，去滓，内胶饴，更上微火消解。',
  },
  大建中汤: {
    formula: '大建中汤',
    source: '金匮要略',
    chapter: '腹满寒疝宿食病篇',
    originalText: '心胸中大寒痛，呕不能饮食，腹中寒，上冲皮起，出见有头足，上下痛而不可触近者，大建中汤主之。',
    keySymptoms: ['心胸中大寒痛', '呕不能饮食', '腹中寒', '上冲皮起', '上下痛而不可触近', '脉沉紧'],
    mechanism: '中焦虚寒，阴寒内盛',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒重证', '阴寒内盛'],
    contraindications: ['热证腹痛'],
    dosage: '蜀椒6g，干姜12g，人参6g',
    instructions: '水煎服，去滓，内胶饴一升，微火煎取一升半。',
  },
  黄芪建中汤: {
    formula: '黄芪建中汤',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '虚劳里急，诸不足，黄芪建中汤主之。',
    keySymptoms: ['里急', '腹痛', '自汗', '面色无华', '脉大而虚'],
    mechanism: '气血两虚，中气不足',
    treatmentMethod: '补益',
    indications: ['虚劳里急', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '黄芪9g，桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '同小建中汤法。',
  },
  当归建中汤: {
    formula: '当归建中汤',
    source: '金匮要略',
    chapter: '产后病篇',
    originalText: '产后虚羸不足，腹中刺痛不止，吸吸少气，或苦少腹中急，摩痛引腰背，不能食饮，当归建中汤主之。',
    keySymptoms: ['腹中刺痛不止', '吸吸少气', '少腹中急', '摩痛引腰背', '不能食饮', '脉细涩'],
    mechanism: '产后气血两虚，中焦不足',
    treatmentMethod: '养血和血',
    indications: ['产后虚劳', '气血两虚'],
    contraindications: ['产后血热'],
    dosage: '当归12g，桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '同小建中汤法。',
  },
  桂枝加龙骨牡蛎汤2: {
    formula: '桂枝加龙骨牡蛎汤',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '夫失精家，少腹弦急，阴头寒，目眩，发落，脉极虚芤迟，为清谷，亡血，失精。脉得诸芤动微紧，男子失精，女子梦交，桂枝加龙骨牡蛎汤主之。',
    keySymptoms: ['遗精', '少腹弦急', '阴头寒', '目眩', '发落', '脉极虚芤迟'],
    mechanism: '阴阳两虚，心肾不交，虚阳外越',
    treatmentMethod: '调和营卫',
    indications: ['阴阳两虚遗精', '虚劳失精'],
    contraindications: ['实证遗精'],
    dosage: '桂枝9g，芍药9g，炙甘草6g，生姜9g，大枣12枚，龙骨15g，牡蛎15g',
    instructions: '水煎服。',
  },
  薯蓣丸: {
    formula: '薯蓣丸',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '虚劳诸不足，风气百疾，薯蓣丸主之。',
    keySymptoms: ['虚劳诸不足', '风气百疾', '形体消瘦', '乏力', '脉微弱'],
    mechanism: '气血阴阳两虚，风邪外袭',
    treatmentMethod: '补益',
    indications: ['虚劳诸不足', '气血两虚'],
    contraindications: ['实证'],
    dosage: '薯蓣30g，当归9g，桂枝9g，神曲9g，干姜3g，大豆黄卷9g，人参6g，白术6g，芍药6g，川芎6g，麦门冬6g，杏仁6g，柴胡6g，桔梗6g，茯苓6g，阿胶6g，干地黄6g，防风6g，白蔹3g，甘草9g，大枣30枚',
    instructions: '为丸，如弹子大，每服1丸，日二服。',
  },

  // 其他太阴病方剂（6个）
  四逆汤: {
    formula: '四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，脉沉者，急温之，宜四逆汤。',
    keySymptoms: ['手足厥冷', '恶寒蜷卧', '下利清谷', '脉微欲绝'],
    mechanism: '少阴阳虚，阴寒内盛',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化证', '阳虚厥逆'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，甘草6g',
    instructions: '水煎服。',
  },
  通脉四逆汤: {
    formula: '通脉四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利清谷，里寒外热，手足厥逆，脉微欲绝，身反不恶寒，其人面色赤，或腹痛，或干呕，或咽痛，或利止脉不出者，通脉四逆汤主之。',
    keySymptoms: ['下利清谷', '手足厥逆', '脉微欲绝', '身反不恶寒', '面色赤', '脉微欲绝'],
    mechanism: '少阴寒化，阴盛格阳',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化重证', '阴盛格阳'],
    contraindications: ['热厥'],
    dosage: '附子12g（大者，生用），干姜9g（强人可至12g），甘草6g',
    instructions: '水煎服。',
  },
  白通汤: {
    formula: '白通汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利，白通汤主之。',
    keySymptoms: ['下利', '面赤', '脉微'],
    mechanism: '少阴寒化，虚阳上越',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化', '虚阳上越'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，葱白4茎',
    instructions: '水煎服。',
  },
  白通加猪胆汁汤: {
    formula: '白通加猪胆汁汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利脉微者，与白通汤。利不止，厥逆无脉，干呕烦者，白通加猪胆汁汤主之。',
    keySymptoms: ['下利不止', '厥逆无脉', '干呕烦', '脉微'],
    mechanism: '少阴寒化，阴盛格阳，热药寒服',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化重证', '阴盛格阳'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，葱白4茎，猪胆汁20ml',
    instructions: '水煎服，纳猪胆汁搅和。',
  },
  茯苓四逆汤2: {
    formula: '茯苓四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，二三日不已，至四五日，腹痛，小便不利，四肢沉重疼痛，自下利者，此为有水气。其人或咳，或小便利，或下利，或呕者，茯苓四逆汤主之。',
    keySymptoms: ['腹痛', '小便不利', '四肢沉重疼痛', '下利', '脉沉微'],
    mechanism: '少阴阳虚，水气内停',
    treatmentMethod: '化饮',
    indications: ['少阴阳虚水停', '阳虚水肿'],
    contraindications: ['阴虚水肿'],
    dosage: '茯苓12g，人参6g，附子6g（生用），甘草6g，干姜6g',
    instructions: '水煎服。',
  },
  干姜附子汤: {
    formula: '干姜附子汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '下之后，复发汗，昼日烦躁不得眠，夜而安静，不呕，不渴，无表证，脉沉微，身无大热者，干姜附子汤主之。',
    keySymptoms: ['昼日烦躁不得眠', '夜而安静', '脉沉微', '身无大热'],
    mechanism: '阳气暴虚，阴寒内盛',
    treatmentMethod: '回阳救逆',
    indications: ['阳气暴虚', '阴寒内盛'],
    contraindications: ['热证烦躁'],
    dosage: '干姜6g，附子9g（生用）',
    instructions: '水煎服，顿服。',
  },
};

// 导出所有太阴病方剂
export const getAllTaiyinFormulas = (): FormulaEvidence[] => {
  return Object.values(TAIYIN_FORMULAS);
};

// ============================================
// 少阴病方剂（50个）
// ============================================

export const SHAOYIN_FORMULAS: Record<string, FormulaEvidence> = {
  // 四逆汤系列（15个）
  四逆汤2: {
    formula: '四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，脉沉者，急温之，宜四逆汤。',
    keySymptoms: ['手足厥冷', '恶寒蜷卧', '下利清谷', '脉微欲绝'],
    mechanism: '少阴阳虚，阴寒内盛',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化证', '阳虚厥逆'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，甘草6g',
    instructions: '水煎服。',
  },
  通脉四逆汤2: {
    formula: '通脉四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利清谷，里寒外热，手足厥逆，脉微欲绝，身反不恶寒，其人面色赤，或腹痛，或干呕，或咽痛，或利止脉不出者，通脉四逆汤主之。',
    keySymptoms: ['下利清谷', '手足厥逆', '脉微欲绝', '身反不恶寒', '面色赤'],
    mechanism: '少阴寒化，阴盛格阳',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化重证', '阴盛格阳'],
    contraindications: ['热厥'],
    dosage: '附子12g（生用），干姜9g，甘草6g',
    instructions: '水煎服。',
  },
  白通汤2: {
    formula: '白通汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利，白通汤主之。',
    keySymptoms: ['下利', '面赤', '脉微'],
    mechanism: '少阴寒化，虚阳上越',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化', '虚阳上越'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，葱白4茎',
    instructions: '水煎服。',
  },
  白通加猪胆汁汤2: {
    formula: '白通加猪胆汁汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利脉微者，与白通汤。利不止，厥逆无脉，干呕烦者，白通加猪胆汁汤主之。',
    keySymptoms: ['下利不止', '厥逆无脉', '干呕烦', '脉微'],
    mechanism: '少阴寒化，阴盛格阳，热药寒服',
    treatmentMethod: '回阳救逆',
    indications: ['少阴寒化重证', '阴盛格阳'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，葱白4茎，猪胆汁20ml',
    instructions: '水煎服，纳猪胆汁搅和。',
  },
  四逆加人参汤: {
    formula: '四逆加人参汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '恶寒脉微而复利，利止，亡血也，四逆加人参汤主之。',
    keySymptoms: ['恶寒', '脉微', '复利', '利止', '亡血'],
    mechanism: '少阴阳虚，气血两伤',
    treatmentMethod: '回阳救逆',
    indications: ['少阴阳虚气血两伤', '亡血'],
    contraindications: ['热证'],
    dosage: '附子9g（生用），干姜6g，甘草6g，人参6g',
    instructions: '水煎服。',
  },
  茯苓四逆汤3: {
    formula: '茯苓四逆汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，二三日不已，至四五日，腹痛，小便不利，四肢沉重疼痛，自下利者，此为有水气。其人或咳，或小便利，或下利，或呕者，茯苓四逆汤主之。',
    keySymptoms: ['腹痛', '小便不利', '四肢沉重疼痛', '下利', '脉沉微'],
    mechanism: '少阴阳虚，水气内停',
    treatmentMethod: '化饮',
    indications: ['少阴阳虚水停', '阳虚水肿'],
    contraindications: ['阴虚水肿'],
    dosage: '茯苓12g，人参6g，附子6g（生用），甘草6g，干姜6g',
    instructions: '水煎服。',
  },
  干姜附子汤2: {
    formula: '干姜附子汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '下之后，复发汗，昼日烦躁不得眠，夜而安静，不呕，不渴，无表证，脉沉微，身无大热者，干姜附子汤主之。',
    keySymptoms: ['昼日烦躁不得眠', '夜而安静', '脉沉微', '身无大热'],
    mechanism: '阳气暴虚，阴寒内盛',
    treatmentMethod: '回阳救逆',
    indications: ['阳气暴虚', '阴寒内盛'],
    contraindications: ['热证烦躁'],
    dosage: '干姜6g，附子9g（生用）',
    instructions: '水煎服，顿服。',
  },
  附子汤: {
    formula: '附子汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，得之一二日，口中和，其背恶寒者，当灸之，附子汤主之。',
    keySymptoms: ['背恶寒', '口中和', '身体痛', '手足寒', '骨节痛', '脉沉'],
    mechanism: '少阴阳虚，寒湿内盛',
    treatmentMethod: '温经散寒',
    indications: ['少阴寒湿', '阳虚寒湿'],
    contraindications: ['风湿热痹'],
    dosage: '附子9g（炮），茯苓9g，人参6g，白术12g，芍药9g',
    instructions: '水煎服。',
  },
  真武汤: {
    formula: '真武汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，二三日不已，至四五日，腹痛，小便不利，四肢沉重疼痛，自下利者，此为有水气。其人或咳，或小便利，或下利，或呕者，真武汤主之。',
    keySymptoms: ['腹痛', '小便不利', '四肢沉重疼痛', '下利', '心下悸', '头眩', '身瞤动', '振振欲擗地'],
    mechanism: '脾肾阳虚，水气内停',
    treatmentMethod: '温经散寒',
    indications: ['脾肾阳虚水停', '阳虚水肿'],
    contraindications: ['阴虚水肿'],
    dosage: '茯苓9g，芍药9g，白术6g，生姜9g，附子6g（炮）',
    instructions: '水煎服。',
  },
  桂枝去芍药加麻黄细辛附子汤: {
    formula: '桂枝去芍药加麻黄细辛附子汤',
    source: '金匮要略',
    chapter: '水气病篇',
    originalText: '气分，心下坚大如盘，边如旋杯，水饮所作，桂枝去芍药加麻黄细辛附子汤主之。',
    keySymptoms: ['心下坚大如盘', '边如旋杯', '手足厥冷', '脉沉紧'],
    mechanism: '阳虚阴凝，水饮内停',
    treatmentMethod: '通阳化饮',
    indications: ['阳虚阴凝', '水饮内停'],
    contraindications: ['阴虚证'],
    dosage: '桂枝9g，甘草6g，麻黄6g，细辛3g，附子6g（炮），生姜9g，大枣4枚',
    instructions: '水煎服，先煮麻黄。',
  },
  麻黄附子甘草汤2: {
    formula: '麻黄附子甘草汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，得之二三日，麻黄附子甘草汤微发汗。以二三日无证，故微发汗也。',
    keySymptoms: ['恶寒', '发热', '无汗', '脉沉'],
    mechanism: '少阴感寒，阳气不足',
    treatmentMethod: '温经散寒',
    indications: ['少阴感寒', '阳虚外感'],
    contraindications: ['少阴热化证'],
    dosage: '麻黄6g，附子6g（炮），炙甘草3g',
    instructions: '水煎服。',
  },
  麻黄附子细辛汤2: {
    formula: '麻黄附子细辛汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，始得之，反发热，脉沉者，麻黄附子细辛汤主之。',
    keySymptoms: ['发热', '恶寒', '无汗', '脉沉'],
    mechanism: '少阴感寒，阳气被郁',
    treatmentMethod: '温经散寒',
    indications: ['少阴感寒初起', '阳虚外感'],
    contraindications: ['少阴热化证'],
    dosage: '麻黄6g，附子6g（炮），细辛3g',
    instructions: '水煎服。',
  },
  附子粳米汤: {
    formula: '附子粳米汤',
    source: '金匮要略',
    chapter: '腹满寒疝宿食病篇',
    originalText: '腹中寒气，雷鸣切痛，胸胁逆满，呕吐，附子粳米汤主之。',
    keySymptoms: ['腹中寒气', '雷鸣切痛', '胸胁逆满', '呕吐', '脉沉紧'],
    mechanism: '脾胃虚寒，寒气上逆',
    treatmentMethod: '温中健脾',
    indications: ['脾胃虚寒', '寒气上逆'],
    contraindications: ['热证腹痛'],
    dosage: '附子6g（炮），半夏9g，甘草6g，大枣4枚，粳米15g',
    instructions: '水煎服。',
  },
  大建中汤2: {
    formula: '大建中汤',
    source: '金匮要略',
    chapter: '腹满寒疝宿食病篇',
    originalText: '心胸中大寒痛，呕不能饮食，腹中寒，上冲皮起，出见有头足，上下痛而不可触近者，大建中汤主之。',
    keySymptoms: ['心胸中大寒痛', '呕不能饮食', '腹中寒', '上冲皮起', '上下痛而不可触近', '脉沉紧'],
    mechanism: '中焦虚寒，阴寒内盛',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒重证', '阴寒内盛'],
    contraindications: ['热证腹痛'],
    dosage: '蜀椒6g，干姜12g，人参6g',
    instructions: '水煎服。',
  },
  小建中汤3: {
    formula: '小建中汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '伤寒二三日，心中悸而烦者，小建中汤主之。',
    keySymptoms: ['心中悸', '烦', '腹中急痛', '面色无华', '脉细涩'],
    mechanism: '中焦虚寒，气血不足',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '水煎服。',
  },

  // 黄连阿胶汤系列（5个）
  黄连阿胶汤: {
    formula: '黄连阿胶汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，得之二三日以上，心中烦，不得卧，黄连阿胶汤主之。',
    keySymptoms: ['心中烦', '不得卧', '口干咽燥', '舌红少苔', '脉细数'],
    mechanism: '少阴热化，阴虚火旺',
    treatmentMethod: '养阴清热',
    indications: ['少阴热化证', '阴虚火旺'],
    contraindications: ['少阴寒化证'],
    dosage: '黄连12g，黄芩6g，芍药6g，阿胶9g，鸡子黄2枚',
    instructions: '水煎服，去滓，内阿胶烊尽，小冷，内鸡子黄，搅令相得。',
  },
  猪肤汤: {
    formula: '猪肤汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利咽痛，胸满心烦，猪肤汤主之。',
    keySymptoms: ['下利', '咽痛', '胸满心烦', '口干'],
    mechanism: '少阴热化，阴虚火旺，肺肾阴虚',
    treatmentMethod: '养阴清热',
    indications: ['少阴热化', '肺肾阴虚'],
    contraindications: ['少阴寒化证'],
    dosage: '猪肤15g',
    instructions: '水一斗，煮取五升，去滓，加白蜜一升，白粉五合，熬香和令相得。',
  },
  甘草汤2: {
    formula: '甘草汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，二三日，咽痛者，可与甘草汤。',
    keySymptoms: ['咽痛', '咽干', '脉细数'],
    mechanism: '热客咽喉，经脉不利',
    treatmentMethod: '清热',
    indications: ['少阴咽痛轻证', '热客咽喉'],
    contraindications: ['虚寒咽痛'],
    dosage: '甘草12g',
    instructions: '水煎服。',
  },
  桔梗汤2: {
    formula: '桔梗汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，二三日，咽痛者，可与甘草汤；不瘥者，与桔梗汤。',
    keySymptoms: ['咽痛', '咳嗽', '咯痰不爽', '脉细数'],
    mechanism: '热客咽喉，肺气不宣',
    treatmentMethod: '清热',
    indications: ['少阴咽痛', '肺热咳嗽'],
    contraindications: ['虚寒咽痛'],
    dosage: '桔梗6g，甘草12g',
    instructions: '水煎服。',
  },
  半夏散及汤2: {
    formula: '半夏散及汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，咽中痛，半夏散及汤主之。',
    keySymptoms: ['咽痛', '咽喉不利', '痰多', '脉沉'],
    mechanism: '寒客咽喉，痰气交阻',
    treatmentMethod: '温经散寒',
    indications: ['少阴寒客咽喉', '寒痰阻滞'],
    contraindications: ['热证咽痛'],
    dosage: '半夏6g，桂枝6g，甘草3g',
    instructions: '为散，每服3g，或水煎服。',
  },

  // 其他少阴病方剂（30个）
  桃花汤: {
    formula: '桃花汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利便脓血者，桃花汤主之。',
    keySymptoms: ['下利便脓血', '腹痛喜按', '小便不利', '脉沉微'],
    mechanism: '少阴滑脱，脾肾阳虚',
    treatmentMethod: '涩肠固脱',
    indications: ['少阴滑脱', '脾肾阳虚便脓血'],
    contraindications: ['湿热便脓血'],
    dosage: '赤石脂24g（一半整用，一半筛末），干姜6g，粳米15g',
    instructions: '水煎服，纳赤石脂末，温服。',
  },
  赤石脂禹余粮汤: {
    formula: '赤石脂禹余粮汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '伤寒服汤药，下利不止，心下痞硬。服泻心汤已，复以他药下之，利不止，医以理中与之，利益甚。理中者，理中焦，此利在下焦，赤石脂禹余粮汤主之。',
    keySymptoms: ['下利不止', '滑脱不禁', '脉沉微'],
    mechanism: '下元不固，滑脱不禁',
    treatmentMethod: '涩肠固脱',
    indications: ['下元不固', '滑脱不禁'],
    contraindications: ['湿热下利'],
    dosage: '赤石脂15g，禹余粮15g',
    instructions: '水煎服。',
  },
  猪苓汤2: {
    formula: '猪苓汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，下利六七日，咳而呕渴，心烦不得眠者，猪苓汤主之。',
    keySymptoms: ['下利', '咳', '呕渴', '心烦不得眠', '小便不利', '脉细数'],
    mechanism: '水热互结，阴虚水停',
    treatmentMethod: '化饮',
    indications: ['阴虚水热互结', '小便不利'],
    contraindications: ['阳虚水肿'],
    dosage: '猪苓9g，茯苓9g，泽泻9g，阿胶9g，滑石9g',
    instructions: '水煎服。',
  },
  吴茱萸汤3: {
    formula: '吴茱萸汤',
    source: '伤寒论',
    chapter: '少阴病篇',
    originalText: '少阴病，吐利，手足逆冷，烦躁欲死者，吴茱萸汤主之。',
    keySymptoms: ['吐利', '手足逆冷', '烦躁欲死', '头痛', '干呕'],
    mechanism: '少阴寒化，阴寒内盛，胃寒上逆',
    treatmentMethod: '温里',
    indications: ['少阴寒化', '胃寒呕吐'],
    contraindications: ['胃热呕吐'],
    dosage: '吴茱萸9g，人参9g，生姜18g，大枣4枚',
    instructions: '水煎服。',
  },
  真人养脏汤: {
    formula: '真人养脏汤',
    source: '太平惠民和剂局方',
    chapter: '脾胃方剂',
    originalText: '治大人小儿肠胃虚弱，冷热不调，脏腑受寒，下利赤白，或便脓血，里急后重，脐腹绞痛，日夜无度，脱肛坠下。',
    keySymptoms: ['下利赤白', '便脓血', '里急后重', '脐腹绞痛', '脱肛坠下', '脉沉细'],
    mechanism: '脾肾虚寒，滑脱不禁',
    treatmentMethod: '涩肠固脱',
    indications: ['脾肾虚寒滑脱', '久利脱肛'],
    contraindications: ['湿热下利'],
    dosage: '人参9g，当归9g，白术9g，肉豆蔻6g，肉桂6g，甘草6g，白芍9g，木香6g，诃子6g，罂粟壳6g',
    instructions: '水煎服。',
  },
  四神丸: {
    formula: '四神丸',
    source: '内科摘要',
    chapter: '脾胃方剂',
    originalText: '治脾肾虚弱，大便不实，五更腹痛，或纯泻清水，或完谷不化，不思饮食，食不消化。',
    keySymptoms: ['五更腹痛', '五更泻', '完谷不化', '不思饮食', '脉沉细'],
    mechanism: '脾肾阳虚，五更泻',
    treatmentMethod: '温里',
    indications: ['脾肾阳虚五更泻', '五更泻'],
    contraindications: ['湿热下利'],
    dosage: '肉豆蔻6g，补骨脂12g，五味子6g，吴茱萸6g',
    instructions: '为丸，每服9g，临睡服。',
  },
  右归丸: {
    formula: '右归丸',
    source: '景岳全书',
    chapter: '补肾方剂',
    originalText: '治元阳不足，或先天禀衰，或劳伤过度，以致命门火衰，不能生土，而为脾胃虚寒，饮食少进，或呕恶膨胀，或翻胃噎膈，或脐腹多痛，或大便不实，或泻痢频作，或小便自遗，或虚淋寒疝，或寒浸湿肿，或肢节痹痛，或寒在下焦，而水邪浮肿。',
    keySymptoms: ['命门火衰', '脾胃虚寒', '饮食少进', '呕恶膨胀', '小便自遗', '肢节痹痛', '脉沉细'],
    mechanism: '命门火衰，脾肾阳虚',
    treatmentMethod: '补益',
    indications: ['命门火衰', '脾肾阳虚'],
    contraindications: ['阴虚火旺'],
    dosage: '熟地黄24g，山药12g，山茱萸9g，枸杞子12g，菟丝子12g，鹿角胶12g，杜仲12g，肉桂6g，当归9g，制附子6g',
    instructions: '为丸，每服9g，日二服。',
  },
  金匮肾气丸: {
    formula: '金匮肾气丸',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '虚劳腰痛，少腹拘急，小便不利者，八味肾气丸主之。',
    keySymptoms: ['腰痛', '少腹拘急', '小便不利', '畏寒肢冷', '脉沉细'],
    mechanism: '肾阳不足，水液代谢失常',
    treatmentMethod: '补益',
    indications: ['肾阳不足', '肾虚水肿'],
    contraindications: ['阴虚火旺'],
    dosage: '干地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，桂枝3g，附子3g（炮）',
    instructions: '为丸，每服9g，日二服。',
  },
  济生肾气丸: {
    formula: '济生肾气丸',
    source: '济生方',
    chapter: '补肾方剂',
    originalText: '治肾虚腰重脚肿，小便不利，或肚腹肿胀，四肢浮肿，喘急痰盛，已成蛊证。',
    keySymptoms: ['腰重脚肿', '小便不利', '肚腹肿胀', '四肢浮肿', '喘急痰盛', '脉沉细'],
    mechanism: '肾阳虚衰，水湿内停',
    treatmentMethod: '补益',
    indications: ['肾阳虚衰水肿', '肾虚水肿'],
    contraindications: ['阴虚火旺'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，肉桂6g，制附子6g，川牛膝9g，车前子9g',
    instructions: '为丸，每服9g，日二服。',
  },
  都气丸: {
    formula: '都气丸',
    source: '症因脉治',
    chapter: '补肾方剂',
    originalText: '治肺肾两虚，咳嗽气喘，呃逆滑精，腰痛。',
    keySymptoms: ['咳嗽气喘', '呃逆滑精', '腰痛', '脉沉细'],
    mechanism: '肺肾两虚，肾不纳气',
    treatmentMethod: '补益',
    indications: ['肺肾两虚', '肾不纳气'],
    contraindications: ['痰热咳嗽'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，五味子6g',
    instructions: '为丸，每服9g，日二服。',
  },
  左归丸: {
    formula: '左归丸',
    source: '景岳全书',
    chapter: '补肾方剂',
    originalText: '治真阴肾水不足，不能滋养营卫，渐至衰弱，或虚热往来，自汗盗汗，或神不守舍，血不归原，或虚损伤阴，或遗淋不禁，或气虚昏运，或眼花耳聋，或口燥舌干，或腰酸腿软，凡精髓内亏，津液枯涸等证。',
    keySymptoms: ['虚热往来', '自汗盗汗', '神不守舍', '遗淋不禁', '眼花耳聋', '口燥舌干', '腰酸腿软', '脉细数'],
    mechanism: '真阴不足，肾精亏损',
    treatmentMethod: '滋阴潜阳',
    indications: ['真阴不足', '肾精亏损'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，枸杞子12g，菟丝子12g，鹿角胶12g，龟板胶12g，川牛膝9g',
    instructions: '为丸，每服9g，日二服。',
  },
  六味地黄丸: {
    formula: '六味地黄丸',
    source: '小儿药证直诀',
    chapter: '补肾方剂',
    originalText: '治肾怯失音，囟开不合，神不足，目中白睛多，面色㿠白等。',
    keySymptoms: ['肾怯失音', '囟开不合', '神不足', '目中白睛多', '面色㿠白', '脉细数'],
    mechanism: '肾阴不足，虚热内生',
    treatmentMethod: '滋阴潜阳',
    indications: ['肾阴不足', '虚热内生'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g',
    instructions: '为丸，每服9g，日二服。',
  },
  知柏地黄丸: {
    formula: '知柏地黄丸',
    source: '医宗金鉴',
    chapter: '补肾方剂',
    originalText: '治阴虚火旺，潮热盗汗，口干咽痛，耳鸣遗精，小便短赤。',
    keySymptoms: ['潮热盗汗', '口干咽痛', '耳鸣遗精', '小便短赤', '脉细数'],
    mechanism: '肾阴不足，相火妄动',
    treatmentMethod: '滋阴潜阳',
    indications: ['阴虚火旺', '相火妄动'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，知母9g，黄柏9g',
    instructions: '为丸，每服9g，日二服。',
  },
  杞菊地黄丸: {
    formula: '杞菊地黄丸',
    source: '医级',
    chapter: '补肾方剂',
    originalText: '治肝肾阴虚，两目昏花，视物不明，或眼睛干涩，迎风流泪。',
    keySymptoms: ['两目昏花', '视物不明', '眼睛干涩', '迎风流泪', '脉细数'],
    mechanism: '肝肾阴虚，目失所养',
    treatmentMethod: '滋阴潜阳',
    indications: ['肝肾阴虚', '目疾'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，枸杞子12g，菊花12g',
    instructions: '为丸，每服9g，日二服。',
  },
  麦味地黄丸: {
    formula: '麦味地黄丸',
    source: '寿世保元',
    chapter: '补肾方剂',
    originalText: '治肺肾阴虚，咳嗽喘逆，潮热盗汗。',
    keySymptoms: ['咳嗽喘逆', '潮热盗汗', '咽干口燥', '脉细数'],
    mechanism: '肺肾阴虚，肾不纳气',
    treatmentMethod: '滋阴潜阳',
    indications: ['肺肾阴虚', '肾不纳气'],
    contraindications: ['痰热咳嗽'],
    dosage: '熟地黄24g，山药12g，山茱萸12g，泽泻9g，茯苓9g，牡丹皮9g，麦门冬12g，五味子6g',
    instructions: '为丸，每服9g，日二服。',
  },
  大补阴丸: {
    formula: '大补阴丸',
    source: '丹溪心法',
    chapter: '补肾方剂',
    originalText: '治阴虚火旺，骨蒸潮热，盗汗遗精，咳嗽咯血，心烦易怒，足膝疼热。',
    keySymptoms: ['骨蒸潮热', '盗汗遗精', '咳嗽咯血', '心烦易怒', '足膝疼热', '脉细数'],
    mechanism: '阴虚火旺，相火妄动',
    treatmentMethod: '滋阴潜阳',
    indications: ['阴虚火旺', '相火妄动'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄18g，龟板18g，黄柏12g，知母12g',
    instructions: '为丸，每服9g，日二服。',
  },
  虎潜丸: {
    formula: '虎潜丸',
    source: '丹溪心法',
    chapter: '补肾方剂',
    originalText: '治肝肾不足，筋骨痿软，步履艰难，腰膝酸软。',
    keySymptoms: ['筋骨痿软', '步履艰难', '腰膝酸软', '脉细数'],
    mechanism: '肝肾不足，筋骨失养',
    treatmentMethod: '滋阴潜阳',
    indications: ['肝肾不足', '痿证'],
    contraindications: ['湿热痿证'],
    dosage: '黄柏15g，龟板15g，知母15g，熟地黄15g，陈皮15g，白芍15g，锁阳15g，虎骨15g（现用狗骨代），干姜6g',
    instructions: '为丸，每服9g，日二服。',
  },
  一贯煎: {
    formula: '一贯煎',
    source: '续名医类案',
    chapter: '疏肝方剂',
    originalText: '治肝肾阴虚，血燥气郁，胸脘胁痛，吞酸吐苦，咽干口燥，舌红少津。',
    keySymptoms: ['胸脘胁痛', '吞酸吐苦', '咽干口燥', '舌红少津', '脉弦细数'],
    mechanism: '肝肾阴虚，肝气不舒',
    treatmentMethod: '滋阴潜阳',
    indications: ['肝肾阴虚', '肝气不舒'],
    contraindications: ['肝火炽盛'],
    dosage: '北沙参15g，麦冬15g，当归9g，生地黄20g，枸杞子12g，川楝子6g',
    instructions: '水煎服。',
  },
  酸枣仁汤: {
    formula: '酸枣仁汤',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '虚劳虚烦不得眠，酸枣仁汤主之。',
    keySymptoms: ['虚烦不得眠', '心悸不安', '头目眩晕', '咽干口燥', '脉细数'],
    mechanism: '肝血不足，虚热内扰',
    treatmentMethod: '养阴清热',
    indications: ['肝血不足失眠', '虚烦不眠'],
    contraindications: ['实热失眠'],
    dosage: '酸枣仁15g，甘草6g，知母6g，茯苓6g，川芎6g',
    instructions: '水煎服。',
  },
  天王补心丹: {
    formula: '天王补心丹',
    source: '摄生秘剖',
    chapter: '安神方剂',
    originalText: '治思虑过度，心血不足，怔忡健忘，心口多汗，大便或秘或溏，口舌生疮等证。',
    keySymptoms: ['怔忡健忘', '心口多汗', '大便或秘或溏', '口舌生疮', '脉细数'],
    mechanism: '心肾阴虚，虚热内扰',
    treatmentMethod: '养阴清热',
    indications: ['心肾阴虚', '心神不宁'],
    contraindications: ['心火炽盛'],
    dosage: '人参6g，玄参12g，丹参12g，茯苓12g，五味子6g，远志6g，桔梗6g，当归9g，天冬12g，麦冬12g，柏子仁12g，酸枣仁12g，生地黄12g',
    instructions: '为丸，朱砂为衣，每服9g，日二服。',
  },
  归脾汤: {
    formula: '归脾汤',
    source: '济生方',
    chapter: '补血方剂',
    originalText: '治思虑过度，劳伤心脾，健忘怔忡，惊悸盗汗，食少体倦，面色萎黄，舌淡苔薄白，脉细弱。',
    keySymptoms: ['健忘怔忡', '惊悸盗汗', '食少体倦', '面色萎黄', '舌淡苔薄白', '脉细弱'],
    mechanism: '心脾两虚，气血不足',
    treatmentMethod: '补益',
    indications: ['心脾两虚', '气血不足'],
    contraindications: ['实热证'],
    dosage: '白术12g，茯苓12g，黄芪12g，龙眼肉12g，酸枣仁12g，人参6g，木香6g，甘草3g，当归9g，远志6g',
    instructions: '水煎服，加生姜、大枣。',
  },
  十全大补汤: {
    formula: '十全大补汤',
    source: '太平惠民和剂局方',
    chapter: '补血方剂',
    originalText: '治诸虚不足，五劳七伤，不进饮食，久病虚损，时发潮热，气攻骨脊，拘急疼痛，夜梦遗精，面色萎黄，脚膝无力。',
    keySymptoms: ['诸虚不足', '五劳七伤', '不进饮食', '时发潮热', '夜梦遗精', '面色萎黄', '脚膝无力', '脉细弱'],
    mechanism: '气血两虚，阴阳俱损',
    treatmentMethod: '补益',
    indications: ['气血两虚', '阴阳俱损'],
    contraindications: ['实热证'],
    dosage: '人参6g，白术9g，茯苓9g，甘草6g，当归9g，川芎6g，芍药9g，熟地黄12g，黄芪12g，肉桂3g',
    instructions: '水煎服，加生姜、大枣。',
  },
  人参养荣汤: {
    formula: '人参养荣汤',
    source: '太平惠民和剂局方',
    chapter: '补血方剂',
    originalText: '治积虚损，肌肉消瘦，四肢倦怠，发落毛焦，面色萎黄，短气惊悸，食少无味，心胸痞闷。',
    keySymptoms: ['肌肉消瘦', '四肢倦怠', '发落毛焦', '面色萎黄', '短气惊悸', '食少无味', '心胸痞闷', '脉细弱'],
    mechanism: '气血两虚，心脾不足',
    treatmentMethod: '补益',
    indications: ['气血两虚', '心脾不足'],
    contraindications: ['实热证'],
    dosage: '人参6g，白术9g，茯苓9g，甘草6g，当归9g，白芍9g，熟地黄9g，黄芪12g，陈皮6g，远志6g，肉桂3g，五味子6g',
    instructions: '水煎服，加生姜、大枣。',
  },
};

// 导出所有少阴病方剂
export const getAllShaoyinFormulas = (): FormulaEvidence[] => {
  return Object.values(SHAOYIN_FORMULAS);
};

// ============================================
// 厥阴病方剂（30个）
// ============================================

export const JUEYIN_FORMULAS: Record<string, FormulaEvidence> = {
  // 乌梅丸系列（5个）
  乌梅丸2: {
    formula: '乌梅丸',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '蛔厥者，其人当吐蛔，今病者静，而复时烦者，此为脏寒，蛔上入其膈，故烦，须臾复止，得食而呕又烦者，蛔闻食臭出，其人常自吐蛔。蛔厥者，乌梅丸主之。又主久利。',
    keySymptoms: ['烦闷', '时静时烦', '得食而呕又烦', '常自吐蛔', '手足厥冷', '腹痛时作', '脉沉'],
    mechanism: '脏寒蛔动，寒热错杂',
    treatmentMethod: '清上温下',
    indications: ['蛔厥', '久利', '寒热错杂'],
    contraindications: ['单纯寒证或热证'],
    dosage: '乌梅15g，细辛3g，干姜6g，黄连6g，当归6g，附子6g（炮），蜀椒6g，桂枝6g，人参6g，黄柏6g',
    instructions: '为丸，如梧桐子大，每服10丸，日三服。',
  },
  干姜黄芩黄连人参汤2: {
    formula: '干姜黄芩黄连人参汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒本自寒下，医复吐下之，寒格更逆吐下，若食入口即吐，干姜黄芩黄连人参汤主之。',
    keySymptoms: ['食入口即吐', '下利', '脉弦'],
    mechanism: '上热下寒，寒热格拒',
    treatmentMethod: '清上温下',
    indications: ['上热下寒', '寒热格拒'],
    contraindications: ['单纯热证或寒证'],
    dosage: '干姜6g，黄芩6g，黄连3g，人参6g',
    instructions: '水煎服。',
  },
  麻黄升麻汤2: {
    formula: '麻黄升麻汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒六七日，大下后，寸脉沉而迟，手足厥逆，下部脉不至，喉咽不利，唾脓血，泄利不止者，为难治。麻黄升麻汤主之。',
    keySymptoms: ['咽喉不利', '唾脓血', '泄利不止', '手足厥逆', '脉沉'],
    mechanism: '邪陷厥阴，上热下寒，肺热脾寒',
    treatmentMethod: '清上温下',
    indications: ['上热下寒', '肺热脾寒'],
    contraindications: ['单纯热证或寒证'],
    dosage: '麻黄9g，升麻9g，当归6g，知母6g，黄芩6g，葳蕤6g，芍药3g，天冬3g，桂枝3g，茯苓3g，甘草3g，石膏3g，白术3g，干姜3g',
    instructions: '水煎服，先煮麻黄。',
  },
  当归四逆汤: {
    formula: '当归四逆汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '手足厥寒，脉细欲绝者，当归四逆汤主之。',
    keySymptoms: ['手足厥寒', '脉细欲绝', '腹痛', '四肢冷痛', '脉沉细'],
    mechanism: '血虚寒凝，经脉不通',
    treatmentMethod: '温经散寒',
    indications: ['血虚寒凝', '手足厥寒'],
    contraindications: ['热厥'],
    dosage: '当归12g，桂枝9g，芍药9g，细辛3g，甘草6g，通草6g，大枣8枚',
    instructions: '水煎服。',
  },
  当归四逆加吴茱萸生姜汤: {
    formula: '当归四逆加吴茱萸生姜汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '若其人内有久寒者，宜当归四逆加吴茱萸生姜汤。',
    keySymptoms: ['手足厥寒', '脉细欲绝', '内有久寒', '腹痛', '呕吐清涎', '脉沉紧'],
    mechanism: '血虚寒凝，内有久寒',
    treatmentMethod: '温经散寒',
    indications: ['血虚寒凝', '内有久寒'],
    contraindications: ['热厥'],
    dosage: '当归12g，桂枝9g，芍药9g，细辛3g，甘草6g，通草6g，大枣8枚，吴茱萸6g，生姜12g',
    instructions: '水煎服。',
  },

  // 其他厥阴病方剂（25个）
  白头翁汤: {
    formula: '白头翁汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '热利下重者，白头翁汤主之。',
    keySymptoms: ['下利', '便脓血', '里急后重', '腹痛', '脉数'],
    mechanism: '热毒壅滞肠道，气血两燔',
    treatmentMethod: '清热',
    indications: ['热毒下利', '湿热下利'],
    contraindications: ['虚寒下利'],
    dosage: '白头翁15g，黄柏12g，黄连6g，秦皮12g',
    instructions: '水煎服。',
  },
  白头翁加甘草阿胶汤: {
    formula: '白头翁加甘草阿胶汤',
    source: '金匮要略',
    chapter: '妇人产后病篇',
    originalText: '产后下利虚极，白头翁加甘草阿胶汤主之。',
    keySymptoms: ['产后下利', '虚极', '便脓血', '里急后重', '脉细数'],
    mechanism: '产后体虚，热毒下利',
    treatmentMethod: '清热',
    indications: ['产后热毒下利', '虚极下利'],
    contraindications: ['虚寒下利'],
    dosage: '白头翁15g，黄柏12g，黄连6g，秦皮12g，甘草6g，阿胶9g',
    instructions: '水煎服。',
  },
  桃花汤2: {
    formula: '桃花汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '少阴病，下利便脓血者，桃花汤主之。',
    keySymptoms: ['下利便脓血', '腹痛喜按', '小便不利', '脉沉微'],
    mechanism: '少阴滑脱，脾肾阳虚',
    treatmentMethod: '涩肠固脱',
    indications: ['少阴滑脱', '脾肾阳虚便脓血'],
    contraindications: ['湿热便脓血'],
    dosage: '赤石脂24g（一半整用，一半筛末），干姜6g，粳米15g',
    instructions: '水煎服，纳赤石脂末，温服。',
  },
  赤石脂禹余粮汤2: {
    formula: '赤石脂禹余粮汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒服汤药，下利不止，心下痞硬。服泻心汤已，复以他药下之，利不止，医以理中与之，利益甚。理中者，理中焦，此利在下焦，赤石脂禹余粮汤主之。',
    keySymptoms: ['下利不止', '滑脱不禁', '脉沉微'],
    mechanism: '下元不固，滑脱不禁',
    treatmentMethod: '涩肠固脱',
    indications: ['下元不固', '滑脱不禁'],
    contraindications: ['湿热下利'],
    dosage: '赤石脂15g，禹余粮15g',
    instructions: '水煎服。',
  },
  四逆散2: {
    formula: '四逆散',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '少阴病，四逆，其人或咳，或悸，或小便不利，或腹中痛，或泄利下重者，四逆散主之。',
    keySymptoms: ['四逆', '咳', '悸', '小便不利', '腹中痛', '泄利下重', '脉弦'],
    mechanism: '肝胃不和，阳气内郁',
    treatmentMethod: '疏肝和胃',
    indications: ['肝胃不和', '阳气内郁'],
    contraindications: ['阳虚四逆'],
    dosage: '柴胡6g，芍药6g，枳实6g，甘草6g',
    instructions: '为散，每服6g，或水煎服。',
  },
  逍遥散2: {
    formula: '逍遥散',
    source: '太平惠民和剂局方',
    chapter: '妇科方剂',
    originalText: '治血虚劳倦，五心烦热，肢体疼痛，头目昏重，心悸颊赤，口燥咽干，发热盗汗，减食嗜卧，及血热相搏，月水不调，脐腹胀痛，寒热如疟，又疗室女血弱阴虚，荣卫不和，痰嗽潮热，肌体羸瘦，渐成骨蒸。',
    keySymptoms: ['两胁作痛', '头痛目眩', '口燥咽干', '神疲食少', '月经不调', '乳房胀痛', '脉弦而虚'],
    mechanism: '肝郁血虚，脾弱不运',
    treatmentMethod: '疏肝解郁',
    indications: ['肝郁血虚脾弱', '月经不调'],
    contraindications: ['肝火炽盛'],
    dosage: '柴胡9g，当归9g，白芍9g，白术9g，茯苓9g，甘草4.5g，薄荷3g，煨生姜3g',
    instructions: '为散，每服6-9g，或水煎服。',
  },
  丹栀逍遥散2: {
    formula: '丹栀逍遥散',
    source: '内科摘要',
    chapter: '肝脾不和方剂',
    originalText: '治肝脾血虚，化火生热，或烦躁易怒，或自汗盗汗，或头痛目涩，或颊赤口干，或月经不调，或少腹作痛，或小腹胀坠。',
    keySymptoms: ['烦躁易怒', '自汗盗汗', '头痛目涩', '颊赤口干', '月经不调', '少腹作痛', '脉弦数'],
    mechanism: '肝郁血虚化火',
    treatmentMethod: '疏肝解郁',
    indications: ['肝郁化火', '血虚有热'],
    contraindications: ['肝脾虚寒'],
    dosage: '柴胡9g，当归9g，白芍9g，白术9g，茯苓9g，甘草4.5g，薄荷3g，煨生姜3g，牡丹皮9g，栀子9g',
    instructions: '水煎服。',
  },
  龙胆泻肝汤: {
    formula: '龙胆泻肝汤',
    source: '兰室秘藏',
    chapter: '清肝胆湿热方剂',
    originalText: '治肝胆湿热，胁痛口苦，耳聋耳肿，筋痿阴湿热痒，妇女阴痒，小便淋浊，男子阴肿，囊湿。',
    keySymptoms: ['胁痛口苦', '耳聋耳肿', '筋痿阴湿热痒', '小便淋浊', '男子阴肿', '囊湿', '脉弦数'],
    mechanism: '肝胆湿热，下注二阴',
    treatmentMethod: '清热燥湿',
    indications: ['肝胆湿热', '湿热下注'],
    contraindications: ['肝胆虚寒'],
    dosage: '龙胆草9g，黄芩6g，栀子6g，泽泻9g，木通6g，车前子9g，当归6g，柴胡6g，甘草6g，生地黄12g',
    instructions: '水煎服。',
  },
  柴胡疏肝散: {
    formula: '柴胡疏肝散',
    source: '景岳全书',
    chapter: '疏肝方剂',
    originalText: '治胁肋疼痛，寒热往来。',
    keySymptoms: ['胁肋疼痛', '寒热往来', '胸闷', '喜太息', '脉弦'],
    mechanism: '肝气郁结，疏泄失司',
    treatmentMethod: '疏肝解郁',
    indications: ['肝气郁结', '胁痛'],
    contraindications: ['肝阴不足'],
    dosage: '柴胡6g，陈皮6g，川芎6g，香附6g，枳壳6g，芍药6g，甘草3g',
    instructions: '水煎服。',
  },
  半夏泻心汤3: {
    formula: '半夏泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '但满而不痛者，此为痞，半夏泻心汤主之。',
    keySymptoms: ['心下痞满', '呕吐', '肠鸣', '舌苔黄腻', '脉弦'],
    mechanism: '寒热互结，脾胃不和',
    treatmentMethod: '和解少阳',
    indications: ['寒热互结痞证', '脾胃不和'],
    contraindications: ['单纯热痞或寒痞'],
    dosage: '半夏9g，黄芩6g，干姜6g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  生姜泻心汤3: {
    formula: '生姜泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒汗出解之后，胃中不和，心下痞硬，干噫食臭，胁下有水气，腹中雷鸣，下利者，生姜泻心汤主之。',
    keySymptoms: ['心下痞硬', '干噫食臭', '腹中雷鸣', '下利', '脉弦'],
    mechanism: '水饮内停，胃失和降',
    treatmentMethod: '和解少阳',
    indications: ['水饮痞证', '胃失和降'],
    contraindications: ['无水饮痞证'],
    dosage: '生姜12g，半夏9g，黄芩6g，干姜3g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  甘草泻心汤3: {
    formula: '甘草泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒中风，医反下之，其人下利日数十行，谷不化，腹中雷鸣，心下痞硬而满，干呕心烦不得安。医见心下痞，谓病不尽，复下之，其痞益甚，此非结热，但以胃中虚，客气上逆，故使硬也，甘草泻心汤主之。',
    keySymptoms: ['心下痞硬', '下利日数十行', '腹中雷鸣', '心烦不得安', '脉弦'],
    mechanism: '脾胃虚弱，客气上逆',
    treatmentMethod: '调和脾胃',
    indications: ['脾胃虚弱痞证', '虚痞'],
    contraindications: ['实痞'],
    dosage: '甘草12g，半夏9g，黄芩6g，干姜6g，人参6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  附子泻心汤2: {
    formula: '附子泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '心下痞，而复恶寒汗出者，附子泻心汤主之。',
    keySymptoms: ['心下痞', '恶寒汗出', '脉沉'],
    mechanism: '热结心下，兼肾阳虚',
    treatmentMethod: '温里',
    indications: ['热痞兼阳虚', '胃热肾寒'],
    contraindications: ['单纯热痞'],
    dosage: '大黄6g，黄连3g，黄芩3g，附子6g（炮，别煮取汁）',
    instructions: '三黄麻沸汤渍，附子另煮取汁，合和服。',
  },
  大黄黄连泻心汤2: {
    formula: '大黄黄连泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '心下痞，按之濡，其脉关上浮者，大黄黄连泻心汤主之。',
    keySymptoms: ['心下痞', '按之濡', '脉关上浮'],
    mechanism: '胃热气滞，心下痞满',
    treatmentMethod: '清热',
    indications: ['胃热痞证', '热痞'],
    contraindications: ['脾胃虚寒痞证'],
    dosage: '大黄6g，黄连3g',
    instructions: '麻沸汤渍之，须臾绞去滓，分温再服。',
  },
  生姜泻心汤4: {
    formula: '生姜泻心汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒汗出解之后，胃中不和，心下痞硬，干噫食臭，胁下有水气，腹中雷鸣，下利者，生姜泻心汤主之。',
    keySymptoms: ['心下痞硬', '干噫食臭', '腹中雷鸣', '下利', '脉弦'],
    mechanism: '水饮内停，胃失和降',
    treatmentMethod: '和解少阳',
    indications: ['水饮痞证', '胃失和降'],
    contraindications: ['无水饮痞证'],
    dosage: '生姜12g，半夏9g，黄芩6g，干姜3g，人参6g，甘草6g，黄连3g，大枣4枚',
    instructions: '水煎服。',
  },
  小建中汤4: {
    formula: '小建中汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '伤寒二三日，心中悸而烦者，小建中汤主之。',
    keySymptoms: ['心中悸', '烦', '腹中急痛', '面色无华', '脉细涩'],
    mechanism: '中焦虚寒，气血不足',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '水煎服，去滓，内胶饴，更上微火消解。',
  },
  大建中汤3: {
    formula: '大建中汤',
    source: '金匮要略',
    chapter: '腹满寒疝宿食病篇',
    originalText: '心胸中大寒痛，呕不能饮食，腹中寒，上冲皮起，出见有头足，上下痛而不可触近者，大建中汤主之。',
    keySymptoms: ['心胸中大寒痛', '呕不能饮食', '腹中寒', '上冲皮起', '上下痛而不可触近', '脉沉紧'],
    mechanism: '中焦虚寒，阴寒内盛',
    treatmentMethod: '温中健脾',
    indications: ['中焦虚寒重证', '阴寒内盛'],
    contraindications: ['热证腹痛'],
    dosage: '蜀椒6g，干姜12g，人参6g',
    instructions: '水煎服，去滓，内胶饴一升，微火煎取一升半。',
  },
  黄芪建中汤2: {
    formula: '黄芪建中汤',
    source: '金匮要略',
    chapter: '血痹虚劳病篇',
    originalText: '虚劳里急，诸不足，黄芪建中汤主之。',
    keySymptoms: ['里急', '腹痛', '自汗', '面色无华', '脉大而虚'],
    mechanism: '气血两虚，中气不足',
    treatmentMethod: '补益',
    indications: ['虚劳里急', '气血两虚'],
    contraindications: ['阴虚火旺'],
    dosage: '黄芪9g，桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '同小建中汤法。',
  },
  当归建中汤2: {
    formula: '当归建中汤',
    source: '金匮要略',
    chapter: '产后病篇',
    originalText: '产后虚羸不足，腹中刺痛不止，吸吸少气，或苦少腹中急，摩痛引腰背，不能食饮，当归建中汤主之。',
    keySymptoms: ['腹中刺痛不止', '吸吸少气', '少腹中急', '摩痛引腰背', '不能食饮', '脉细涩'],
    mechanism: '产后气血两虚，中焦不足',
    treatmentMethod: '养血和血',
    indications: ['产后虚劳', '气血两虚'],
    contraindications: ['产后血热'],
    dosage: '当归12g，桂枝9g，甘草6g，大枣6枚，芍药18g，生姜9g，胶饴30g',
    instructions: '同小建中汤法。',
  },
  吴茱萸汤4: {
    formula: '吴茱萸汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '干呕，吐涎沫，头痛者，吴茱萸汤主之。',
    keySymptoms: ['干呕', '吐涎沫', '头痛', '四肢厥冷', '脉沉迟'],
    mechanism: '厥阴寒逆，浊阴上扰',
    treatmentMethod: '温里',
    indications: ['厥阴寒逆', '头痛呕吐'],
    contraindications: ['肝胃热证'],
    dosage: '吴茱萸9g，人参9g，生姜18g，大枣4枚',
    instructions: '水煎服。',
  },
  吴茱萸汤5: {
    formula: '吴茱萸汤',
    source: '金匮要略',
    chapter: '呕吐哕下利病篇',
    originalText: '干呕，吐涎沫，头痛者，吴茱萸汤主之。',
    keySymptoms: ['干呕', '吐涎沫', '头痛', '四肢厥冷', '脉沉迟'],
    mechanism: '厥阴寒逆，浊阴上扰',
    treatmentMethod: '温里',
    indications: ['厥阴寒逆', '头痛呕吐'],
    contraindications: ['肝胃热证'],
    dosage: '吴茱萸9g，人参9g，生姜18g，大枣4枚',
    instructions: '水煎服。',
  },
  理中丸2: {
    formula: '理中丸',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '太阴之为病，腹满而吐，食不下，自利益甚，时腹自痛。若下之，必胸下结硬。',
    keySymptoms: ['腹满', '呕吐', '食不下', '自利', '时腹自痛', '口不渴', '脉沉缓'],
    mechanism: '脾胃虚寒，运化失司',
    treatmentMethod: '温中健脾',
    indications: ['太阴病', '脾胃虚寒'],
    contraindications: ['脾胃湿热', '阳明腑实'],
    dosage: '人参9g，白术9g，干姜9g，甘草9g',
    instructions: '为丸，如鸡子黄大，每服1丸，日三服。',
  },
  理中汤3: {
    formula: '理中汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '霍乱，头痛发热，身疼痛，热多欲饮水者，五苓散主之；寒多不用水者，理中丸主之。',
    keySymptoms: ['霍乱', '吐利交作', '腹中冷痛', '口不渴', '脉沉迟'],
    mechanism: '脾胃虚寒，升降失司',
    treatmentMethod: '温中健脾',
    indications: ['脾胃虚寒吐利', '霍乱寒证'],
    contraindications: ['脾胃湿热吐利'],
    dosage: '人参9g，白术9g，干姜9g，甘草9g',
    instructions: '水煎服。',
  },
  四逆汤3: {
    formula: '四逆汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '大汗出，热不去，内拘急，四肢疼，又下利厥逆而恶寒者，四逆汤主之。',
    keySymptoms: ['大汗出', '热不去', '内拘急', '四肢疼', '下利厥逆而恶寒', '脉微欲绝'],
    mechanism: '阳气亡脱，阴寒内盛',
    treatmentMethod: '回阳救逆',
    indications: ['阳气亡脱', '阴寒内盛'],
    contraindications: ['热厥'],
    dosage: '附子9g（生用），干姜6g，甘草6g',
    instructions: '水煎服。',
  },
  通脉四逆汤3: {
    formula: '通脉四逆汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '下利清谷，里寒外热，汗出而厥者，通脉四逆汤主之。',
    keySymptoms: ['下利清谷', '里寒外热', '汗出而厥', '脉微欲绝', '面赤'],
    mechanism: '阴盛格阳，真寒假热',
    treatmentMethod: '回阳救逆',
    indications: ['阴盛格阳', '真寒假热'],
    contraindications: ['热厥'],
    dosage: '附子12g（生用），干姜9g，甘草6g',
    instructions: '水煎服。',
  },
  当归四逆汤2: {
    formula: '当归四逆汤',
    source: '伤寒论',
    chapter: '厥阴病篇',
    originalText: '手足厥寒，脉细欲绝者，当归四逆汤主之。',
    keySymptoms: ['手足厥寒', '脉细欲绝', '腹痛', '四肢冷痛', '脉沉细'],
    mechanism: '血虚寒凝，经脉不通',
    treatmentMethod: '温经散寒',
    indications: ['血虚寒凝', '手足厥寒'],
    contraindications: ['热厥'],
    dosage: '当归12g，桂枝9g，芍药9g，细辛3g，甘草6g，通草6g，大枣8枚',
    instructions: '水煎服。',
  },
};

// 导出所有厥阴病方剂
export const getAllJueyinFormulas = (): FormulaEvidence[] => {
  return Object.values(JUEYIN_FORMULAS);
};

// 导出所有方剂（总计）
export const getAllFormulas = (): FormulaEvidence[] => {
  return [
    ...getAllSunyangFormulas(),
    ...getAllYangmingFormulas(),
    ...getAllShaoyangFormulas(),
    ...getAllTaiyinFormulas(),
    ...getAllShaoyinFormulas(),
    ...getAllJueyinFormulas(),
  ];
};

// ============================================
// 补充方剂（金匮要略及其他经典方剂）
// ============================================

export const SUPPLEMENTARY_FORMULAS: Record<string, FormulaEvidence> = {
  // 补肾方剂（3个）
  左归饮: {
    formula: '左归饮',
    source: '景岳全书',
    chapter: '补肾方剂',
    originalText: '治真阴肾水不足，不能滋养营卫，渐至衰弱，或虚热往来，自汗盗汗，或神不守舍，血不归原，或虚损伤阴，或遗淋不禁，或气虚昏运，或眼花耳聋，或口燥舌干，或腰酸腿软，凡精髓内亏，津液枯涸等证。',
    keySymptoms: ['真阴不足', '虚热往来', '自汗盗汗', '神不守舍', '遗淋不禁', '眼花耳聋', '口燥舌干', '腰酸腿软', '脉细数'],
    mechanism: '真阴不足，肾精亏损',
    treatmentMethod: '滋阴潜阳',
    indications: ['真阴不足', '肾精亏损'],
    contraindications: ['阳虚证'],
    dosage: '熟地黄12g，山药12g，枸杞子12g，炙甘草6g，茯苓9g，山茱萸9g',
    instructions: '水煎服。',
  },
  右归饮: {
    formula: '右归饮',
    source: '景岳全书',
    chapter: '补肾方剂',
    originalText: '治命门之阳衰阴胜，或先天禀衰，或劳伤过度，以致命门火衰，不能生土，而为脾胃虚寒，饮食少进，或呕恶膨胀，或翻胃噎膈，或脐腹多痛，或大便不实，或泻痢频作，或小便自遗，或虚淋寒疝，或寒浸湿肿，或肢节痹痛，或寒在下焦，而水邪浮肿。',
    keySymptoms: ['命门阳衰', '脾胃虚寒', '饮食少进', '呕恶膨胀', '小便自遗', '肢节痹痛', '脉沉细'],
    mechanism: '命门火衰，脾肾阳虚',
    treatmentMethod: '补益',
    indications: ['命门火衰', '脾肾阳虚'],
    contraindications: ['阴虚火旺'],
    dosage: '熟地黄12g，山药12g，山茱萸9g，枸杞子9g，炙甘草6g，杜仲6g，肉桂6g，制附子6g',
    instructions: '水煎服。',
  },
  七宝美髯丹: {
    formula: '七宝美髯丹',
    source: '本草纲目',
    chapter: '补肾方剂',
    originalText: '乌须发，壮筋骨，固精气，续嗣延年，服之半月，即见功效，久服永无白发。',
    keySymptoms: ['须发早白', '腰膝酸软', '遗精滑泄', '牙齿动摇', '脉细弱'],
    mechanism: '肝肾不足，精血亏虚',
    treatmentMethod: '补益',
    indications: ['肝肾不足', '精血亏虚'],
    contraindications: ['湿热证'],
    dosage: '赤何首乌、白何首乌、赤茯苓、白茯苓、牛膝、当归、枸杞子、菟丝子、补骨脂各9g',
    instructions: '为蜜丸，每服9g，日二服。',
  },

  // 理血方剂（2个）
  桃红四物汤: {
    formula: '桃红四物汤',
    source: '医宗金鉴',
    chapter: '理血方剂',
    originalText: '治妇女经期超前，血多有块，色紫稠粘，腹痛等。',
    keySymptoms: ['月经超前', '血多有块', '色紫稠粘', '腹痛', '脉涩'],
    mechanism: '血瘀兼血虚',
    treatmentMethod: '活血化瘀',
    indications: ['血瘀兼血虚', '痛经'],
    contraindications: ['血热妄行'],
    dosage: '熟地黄12g，当归9g，白芍9g，川芎6g，桃仁6g，红花6g',
    instructions: '水煎服。',
  },
  血府逐瘀汤: {
    formula: '血府逐瘀汤',
    source: '医林改错',
    chapter: '理血方剂',
    originalText: '治头痛胸痛，胸不任物，胸任重物，天亮出汗，食自胸右下，呃逆，干呕，晚发一阵热，内热瞀闷，失眠多梦，心悸怔忡，急躁善怒。',
    keySymptoms: ['头痛胸痛', '失眠多梦', '心悸怔忡', '急躁善怒', '舌紫暗', '脉涩'],
    mechanism: '血瘀胸中，气机不畅',
    treatmentMethod: '活血化瘀',
    indications: ['血瘀胸中', '气滞血瘀'],
    contraindications: ['孕妇', '血虚无瘀'],
    dosage: '桃仁12g，红花9g，当归9g，生地黄9g，川芎4.5g，赤芍6g，牛膝9g，桔梗4.5g，柴胡3g，枳壳6g，甘草3g',
    instructions: '水煎服。',
  },

  // 理气方剂（2个）
  越鞠丸: {
    formula: '越鞠丸',
    source: '丹溪心法',
    chapter: '理气方剂',
    originalText: '统治六郁，胸膈痞闷，吞酸呕吐，饮食不消等。',
    keySymptoms: ['胸膈痞闷', '吞酸呕吐', '饮食不消', '脉弦'],
    mechanism: '气、血、痰、火、湿、食六郁',
    treatmentMethod: '疏肝解郁',
    indications: ['六郁证', '气滞血瘀'],
    contraindications: ['气血两虚'],
    dosage: '香附、川芎、苍术、神曲、栀子各等份',
    instructions: '为水丸，每服6-9g，日二服。',
  },
  柴胡疏肝散: {
    formula: '柴胡疏肝散',
    source: '景岳全书',
    chapter: '理气方剂',
    originalText: '治胁肋疼痛，寒热往来。',
    keySymptoms: ['胁肋疼痛', '寒热往来', '胸闷', '喜太息', '脉弦'],
    mechanism: '肝气郁结，疏泄失司',
    treatmentMethod: '疏肝解郁',
    indications: ['肝气郁结', '胁痛'],
    contraindications: ['肝阴不足'],
    dosage: '柴胡6g，陈皮6g，川芎6g，香附6g，枳壳6g，芍药6g，甘草3g',
    instructions: '水煎服。',
  },

  // 祛痰方剂（1个）
  二陈汤: {
    formula: '二陈汤',
    source: '太平惠民和剂局方',
    chapter: '祛痰方剂',
    originalText: '治湿痰咳嗽，痰多色白易咯，胸膈痞闷，恶心呕吐，肢体困重，或头眩心悸，舌苔白滑或腻，脉滑。',
    keySymptoms: ['咳嗽痰多', '痰白易咯', '胸膈痞闷', '恶心呕吐', '肢体困重', '苔白滑腻', '脉滑'],
    mechanism: '湿痰内盛，肺失宣降',
    treatmentMethod: '和解少阳',
    indications: ['湿痰咳嗽', '痰湿内盛'],
    contraindications: ['燥痰咳嗽'],
    dosage: '半夏9g，橘红9g，茯苓6g，甘草3g',
    instructions: '水煎服，加生姜、乌梅。',
  },
};

// 导出所有方剂（总计，包含补充方剂）
export const getAllFormulasWithSupplementary = (): FormulaEvidence[] => {
  return [
    ...getAllFormulas(),
    ...Object.values(SUPPLEMENTARY_FORMULAS),
  ];
};
